package ellipticcurves

import (
	"math/big"
	"math/rand"
)

// Order returns the order of the group E(F_p); it is an alias for
// CurveOrderNaive.
func (c *CurveFp) Order() *big.Int {
	return c.CurveOrderNaive()
}

// NumberOfPoints returns #E(F_p) including the point at infinity; it is an alias
// for CurveOrderNaive.
func (c *CurveFp) NumberOfPoints() *big.Int {
	return c.CurveOrderNaive()
}

// Contains reports whether pt lies on the curve; it is an alias for IsOnCurve.
func (c *CurveFp) Contains(pt PointFp) bool {
	return c.IsOnCurve(pt)
}

// IsInfinity reports whether pt is the point at infinity.
func (c *CurveFp) IsInfinity(pt PointFp) bool {
	return pt.Infinity
}

// Negate is an alias for Neg.
func (c *CurveFp) Negate(pt PointFp) PointFp {
	return c.Neg(pt)
}

// Cofactor returns #E(F_p) / n, the index of the order-n subgroup, or nil when n
// does not divide the group order.
func (c *CurveFp) Cofactor(n *big.Int) *big.Int {
	order := c.CurveOrderNaive()
	if n.Sign() == 0 || new(big.Int).Mod(order, n).Sign() != 0 {
		return nil
	}
	return new(big.Int).Div(order, n)
}

// SubgroupPoints returns the cyclic subgroup generated by gen as a slice of
// points, starting from the point at infinity and ending just before returning
// to it. Its length equals the order of gen.
func (c *CurveFp) SubgroupPoints(gen PointFp) []PointFp {
	pts := []PointFp{PointAtInfinityFp()}
	if gen.Infinity {
		return pts
	}
	cur := clonePointFp(gen)
	for !cur.Infinity {
		pts = append(pts, clonePointFp(cur))
		cur = c.Add(cur, gen)
	}
	return pts
}

// EmbeddingDegree returns the embedding degree of the order-n subgroup, the
// least k >= 1 with n dividing p^k - 1. It requires gcd(n, p) = 1 and returns 0
// otherwise. The embedding degree governs the smallest field extension carrying
// the full n-torsion and hence the Weil pairing.
func (c *CurveFp) EmbeddingDegree(n *big.Int) *big.Int {
	if Gcd(n, c.P).Cmp(bigOne) != 0 {
		return big.NewInt(0)
	}
	return OrderModN(c.P, n)
}

// TorsionBasisFp returns two points P, Q generating the full n-torsion
// E[n] = Z/n x Z/n over F_p, when it is rational, together with true. It
// requires n^2 to divide #E(F_p) and the n-torsion to be fully rational (which
// forces n to divide p-1). It returns (O, O, false) when no such basis exists.
// Independence is certified by a non-trivial Weil pairing.
func (c *CurveFp) TorsionBasisFp(n *big.Int, rng *rand.Rand) (PointFp, PointFp, bool) {
	order := c.CurveOrderNaive()
	n2 := new(big.Int).Mul(n, n)
	if new(big.Int).Mod(order, n2).Sign() != 0 {
		return PointAtInfinityFp(), PointAtInfinityFp(), false
	}
	p, ok := c.randomPointOfOrder(n, order, rng)
	if !ok {
		return PointAtInfinityFp(), PointAtInfinityFp(), false
	}
	for attempt := 0; attempt < 400; attempt++ {
		q, ok := c.randomPointOfOrder(n, order, rng)
		if !ok {
			continue
		}
		v, err := c.WeilPairing(n, p, q, rng)
		if err != nil {
			continue
		}
		// Independent iff the pairing is a primitive n-th root of unity.
		if MultiplicativeOrder(v, c.P).Cmp(n) == 0 {
			return p, q, true
		}
	}
	return PointAtInfinityFp(), PointAtInfinityFp(), false
}

// randomPointOfOrder returns a random point of exact order n by projecting a
// random point onto the n-Sylow subgroup (multiplying away the coprime part of
// the group order) and then reducing to order n. It works even when the
// n-torsion is non-cyclic, unlike the cofactor method of FindPointOfOrder.
func (c *CurveFp) randomPointOfOrder(n, order *big.Int, rng *rand.Rand) (PointFp, bool) {
	// coprimePart = order with all factors of the primes dividing n removed.
	coprime := new(big.Int).Set(order)
	for _, prime := range PrimeFactors(n) {
		for new(big.Int).Mod(coprime, prime).Sign() == 0 {
			coprime.Div(coprime, prime)
		}
	}
	for attempt := 0; attempt < 400; attempt++ {
		r := c.RandomPointFp(rng)
		pt := c.ScalarMul(coprime, r)
		if pt.Infinity {
			continue
		}
		// Reduce the prime-power order down to exactly n.
		for !c.ScalarMul(n, pt).Infinity {
			pt = c.ScalarMul(n, pt)
		}
		if !pt.Infinity {
			return pt, true
		}
	}
	return PointAtInfinityFp(), false
}

// Multiply is an alias for ScalarMul over the rationals.
func (c *CurveQ) Multiply(k *big.Int, pt PointQ) PointQ {
	return c.ScalarMul(k, pt)
}

// Contains reports whether pt lies on the rational curve; it is an alias for
// IsOnCurve.
func (c *CurveQ) Contains(pt PointQ) bool {
	return c.IsOnCurve(pt)
}

// IsInfinity reports whether pt is the rational point at infinity.
func (c *CurveQ) IsInfinity(pt PointQ) bool {
	return pt.Infinity
}

// Negate is an alias for Neg over the rationals.
func (c *CurveQ) Negate(pt PointQ) PointQ {
	return c.Neg(pt)
}
