package codingtheory

import "errors"

// ErrGenerator is returned when a generator polynomial does not divide x^n-1.
var ErrGenerator = errors.New("codingtheory: generator does not divide x^n - 1")

// PolyToBits converts a GF(2) polynomial packed as an int into a length-n bit
// slice in little-endian order, where index i holds the coefficient of x^i.
func PolyToBits(p, n int) []int {
	out := make([]int, n)
	for i := 0; i < n; i++ {
		out[i] = (p >> uint(i)) & 1
	}
	return out
}

// BitsToPoly converts a little-endian bit slice (index i = coefficient of x^i)
// into a GF(2) polynomial packed as an int.
func BitsToPoly(bits []int) int {
	var p int
	for i, b := range bits {
		if b&1 != 0 {
			p |= 1 << uint(i)
		}
	}
	return p
}

// CyclicCode is a binary cyclic [n,k] code generated by a polynomial g(x) that
// divides x^n-1 over GF(2). Bit slices are little-endian coefficient vectors
// (index i is the coefficient of x^i). Encoding is systematic: the k message
// bits occupy the high-order coefficients and the n-k parity bits the low-order
// ones.
type CyclicCode struct {
	n, k int
	gen  int // generator polynomial, degree n-k
}

// NewCyclicCode builds the cyclic code of length n generated by the polynomial
// gen (packed as an int). It verifies that gen divides x^n-1 and returns
// ErrGenerator otherwise.
func NewCyclicCode(n, gen int) (*CyclicCode, error) {
	if n < 1 || gen == 0 {
		return nil, ErrFieldParam
	}
	xn1 := (1 << uint(n)) ^ 1 // x^n - 1 = x^n + 1
	if GF2PolyMod(xn1, gen) != 0 {
		return nil, ErrGenerator
	}
	deg := GF2PolyDegree(gen)
	return &CyclicCode{n: n, k: n - deg, gen: gen}, nil
}

// N returns the code length.
func (c *CyclicCode) N() int { return c.n }

// K returns the message dimension.
func (c *CyclicCode) K() int { return c.k }

// Generator returns the generator polynomial packed as an int.
func (c *CyclicCode) Generator() int { return c.gen }

// GeneratorBits returns the generator polynomial as a length-(n-k+1) bit slice.
func (c *CyclicCode) GeneratorBits() []int { return PolyToBits(c.gen, c.n-c.k+1) }

// EncodePoly systematically encodes a message polynomial (packed as an int, of
// degree < k) into a code-word polynomial of degree < n.
func (c *CyclicCode) EncodePoly(msg int) int {
	shifted := msg << uint(c.n-c.k)
	parity := GF2PolyMod(shifted, c.gen)
	return shifted ^ parity
}

// Encode systematically encodes a length-k message bit slice into a length-n
// code word. It returns ErrLength if the message length is not k.
func (c *CyclicCode) Encode(msg []int) ([]int, error) {
	if len(msg) != c.k {
		return nil, ErrLength
	}
	if !validBits(msg) {
		return nil, ErrBit
	}
	// message occupies the high-order coefficients x^(n-k) .. x^(n-1)
	m := BitsToPoly(msg)
	cw := c.EncodePoly(m)
	return PolyToBits(cw, c.n), nil
}

// EncodeNonSystematic encodes a message by the direct product c(x)=m(x)*g(x),
// producing a length-n (non-systematic) code word.
func (c *CyclicCode) EncodeNonSystematic(msg []int) ([]int, error) {
	if len(msg) != c.k {
		return nil, ErrLength
	}
	if !validBits(msg) {
		return nil, ErrBit
	}
	cw := GF2PolyMul(BitsToPoly(msg), c.gen)
	return PolyToBits(cw, c.n), nil
}

// SyndromePoly returns the syndrome polynomial r(x) mod g(x) of a received
// word polynomial.
func (c *CyclicCode) SyndromePoly(word int) int { return GF2PolyMod(word, c.gen) }

// Syndrome returns the syndrome of a received length-n word as a bit slice of
// length n-k. A zero syndrome indicates a valid code word.
func (c *CyclicCode) Syndrome(word []int) ([]int, error) {
	if len(word) != c.n {
		return nil, ErrLength
	}
	s := GF2PolyMod(BitsToPoly(word), c.gen)
	return PolyToBits(s, c.n-c.k), nil
}

// IsCodeword reports whether a length-n word is a valid code word.
func (c *CyclicCode) IsCodeword(word []int) bool {
	if len(word) != c.n {
		return false
	}
	return GF2PolyMod(BitsToPoly(word), c.gen) == 0
}

// DecodeMessage extracts the k message bits from a systematic code word,
// reading the high-order coefficients.
func (c *CyclicCode) DecodeMessage(word []int) ([]int, error) {
	if len(word) != c.n {
		return nil, ErrLength
	}
	return append([]int(nil), word[c.n-c.k:]...), nil
}

// GeneratorMatrix returns the k-by-n systematic generator matrix of the code
// with rows in little-endian coefficient order.
func (c *CyclicCode) GeneratorMatrix() [][]int {
	g := make([][]int, c.k)
	for i := 0; i < c.k; i++ {
		// message = x^i (the i-th unit message bit occupies coefficient x^i of
		// the k-bit message, i.e. coefficient x^(n-k+i) of the code word).
		g[i] = PolyToBits(c.EncodePoly(1<<uint(i)), c.n)
	}
	return g
}
