package grouprep

import (
	"fmt"
	"math"
	"math/cmplx"
	"testing"
)

const tol = 1e-9

// ExampleDecomposeCharacter shows that the regular representation of S3
// decomposes with each irreducible appearing with multiplicity equal to its
// degree: the trivial (1), the sign (1) and the two-dimensional standard
// representation (2).
func ExampleCharacterTable_Decompose() {
	g := SymmetricGroup(3)
	ct := CharacterTableSymmetric(3)
	reg := RegularCharacter(g)
	fmt.Println(ct.Decompose(reg))
	// Output: [1 1 2]
}

// ExampleInnerProduct demonstrates the first orthogonality relation on the
// irreducible characters of S3.
func ExampleInnerProduct() {
	g := SymmetricGroup(3)
	ct := CharacterTableSymmetric(3)
	std := ct.Irreducible(2)
	fmt.Printf("%.0f %.0f\n",
		real(InnerProduct(g, std, std)),
		real(InnerProduct(g, ct.Irreducible(0), std)))
	// Output: 1 0
}

func TestGroupBasics(t *testing.T) {
	tests := []struct {
		name     string
		g        *Group
		order    int
		abelian  bool
		classes  int
		exponent int
	}{
		{"C1", TrivialGroup(), 1, true, 1, 1},
		{"C4", CyclicGroup(4), 4, true, 4, 4},
		{"C6", CyclicGroup(6), 6, true, 6, 6},
		{"V4", KleinFourGroup(), 4, true, 4, 2},
		{"D3", DihedralGroup(3), 6, false, 3, 6},
		{"D4", DihedralGroup(4), 8, false, 5, 4},
		{"D5", DihedralGroup(5), 10, false, 4, 10},
		{"S3", SymmetricGroup(3), 6, false, 3, 6},
		{"S4", SymmetricGroup(4), 24, false, 5, 12},
		{"A4", AlternatingGroup(4), 12, false, 4, 6},
		{"Q8", QuaternionGroup(), 8, false, 5, 4},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := tc.g.Order(); got != tc.order {
				t.Errorf("Order = %d, want %d", got, tc.order)
			}
			if got := tc.g.IsAbelian(); got != tc.abelian {
				t.Errorf("IsAbelian = %v, want %v", got, tc.abelian)
			}
			if got := tc.g.NumConjugacyClasses(); got != tc.classes {
				t.Errorf("NumConjugacyClasses = %d, want %d", got, tc.classes)
			}
			if got := tc.g.Exponent(); got != tc.exponent {
				t.Errorf("Exponent = %d, want %d", got, tc.exponent)
			}
			if err := tc.g.IsValid(); err != nil {
				t.Errorf("IsValid: %v", err)
			}
		})
	}
}

func TestGroupInverseAndOrder(t *testing.T) {
	g := DihedralGroup(4)
	for i := 0; i < g.Order(); i++ {
		if g.Mul(i, g.Inverse(i)) != g.Identity() {
			t.Errorf("element %d times its inverse is not identity", i)
		}
		ord := g.ElementOrder(i)
		if g.Pow(i, ord) != g.Identity() {
			t.Errorf("element %d^%d != identity", i, ord)
		}
	}
	// r has order 4, s has order 2.
	if g.ElementOrder(1) != 4 { // r^1
		t.Errorf("order of r = %d, want 4", g.ElementOrder(1))
	}
	if g.ElementOrder(4) != 2 { // s
		t.Errorf("order of s = %d, want 2", g.ElementOrder(4))
	}
}

func TestCenterAndSubgroup(t *testing.T) {
	// Center of Q8 is {1, -1}.
	q := QuaternionGroup()
	center := q.Center()
	if len(center) != 2 || center[0] != 0 || center[1] != 1 {
		t.Errorf("Center(Q8) = %v, want [0 1]", center)
	}
	// Rotations form a subgroup of D4.
	d := DihedralGroup(4)
	rot := []int{0, 1, 2, 3}
	if !d.IsSubgroup(rot) {
		t.Errorf("rotations should be a subgroup of D4")
	}
	gen := d.GeneratedBy([]int{1}) // generated by r
	if len(gen) != 4 {
		t.Errorf("〈r〉 has %d elements, want 4", len(gen))
	}
}

func TestMatrixArithmetic(t *testing.T) {
	a := MatrixFromReal([][]float64{{1, 2}, {3, 4}})
	if got := a.Det(); !ApproxEqualC(got, complex(-2, 0), tol) {
		t.Errorf("Det = %v, want -2", got)
	}
	inv, err := a.Inverse()
	if err != nil {
		t.Fatalf("Inverse: %v", err)
	}
	prod := mustMul(a, inv)
	if !prod.IsIdentity(tol) {
		t.Errorf("a·a⁻¹ not identity:\n%v", prod)
	}
	if !ApproxEqualC(a.Trace(), complex(5, 0), tol) {
		t.Errorf("Trace = %v, want 5", a.Trace())
	}
}

func TestKroneckerTrace(t *testing.T) {
	a := MatrixFromReal([][]float64{{1, 0}, {0, 2}})
	b := MatrixFromReal([][]float64{{3, 1}, {1, 3}})
	k := a.Kronecker(b)
	if k.Rows() != 4 || k.Cols() != 4 {
		t.Fatalf("Kronecker shape %dx%d, want 4x4", k.Rows(), k.Cols())
	}
	// tr(A⊗B) = tr(A)·tr(B).
	if !ApproxEqualC(k.Trace(), a.Trace()*b.Trace(), tol) {
		t.Errorf("tr(A⊗B) = %v, want %v", k.Trace(), a.Trace()*b.Trace())
	}
}

func TestPermutation(t *testing.T) {
	p := Perm{1, 2, 0} // 3-cycle
	if p.Sign() != 1 {
		t.Errorf("sign of 3-cycle = %d, want 1", p.Sign())
	}
	if p.Order() != 3 {
		t.Errorf("order of 3-cycle = %d, want 3", p.Order())
	}
	q := Perm{1, 0, 2} // transposition
	if q.Sign() != -1 {
		t.Errorf("sign of transposition = %d, want -1", q.Sign())
	}
	// p∘p⁻¹ = identity.
	id := p.Compose(p.Inverse())
	if !id.Equal(IdentityPerm(3)) {
		t.Errorf("p∘p⁻¹ = %v, want identity", id)
	}
	if len(AllPermutations(4)) != 24 {
		t.Errorf("AllPermutations(4) has %d entries, want 24", len(AllPermutations(4)))
	}
}

func TestRepsAreHomomorphisms(t *testing.T) {
	reps := map[string]*Rep{
		"trivial-S3":  TrivialRep(SymmetricGroup(3)),
		"regular-S3":  RegularRep(SymmetricGroup(3)),
		"cyclic-C5-2": CyclicRep(5, 2),
		"dihedral-D4": DihedralRep2D(4, 1),
		"dihedral-D5": DihedralRep2D(5, 2),
		"natural-S4":  NaturalRepSymmetric(4),
		"sign-S4":     SignRepSymmetric(4),
		"quaternion":  QuaternionRep(),
	}
	for name, r := range reps {
		t.Run(name, func(t *testing.T) {
			if !r.IsHomomorphism(tol) {
				t.Errorf("%s is not a homomorphism", name)
			}
		})
	}
}

func TestNewRepValidation(t *testing.T) {
	g := CyclicGroup(3)
	// A valid rep built from matrices.
	r := CyclicRep(3, 1)
	mats := make([]Matrix, g.Order())
	for i := 0; i < g.Order(); i++ {
		mats[i] = r.Matrix(i)
	}
	if _, err := NewRep(g, mats, tol); err != nil {
		t.Errorf("NewRep on valid data: %v", err)
	}
	// Break the homomorphism.
	mats[1] = Matrix{{2}}
	if _, err := NewRep(g, mats, tol); err == nil {
		t.Errorf("NewRep should reject a non-homomorphism")
	}
}

func TestUnitaryReps(t *testing.T) {
	for _, r := range []*Rep{
		RegularRep(DihedralGroup(4)),
		DihedralRep2D(5, 1),
		QuaternionRep(),
		CyclicRep(7, 3),
	} {
		if !r.IsUnitary(tol) {
			t.Errorf("%s should be unitary", r.RepString())
		}
	}
}

func TestCharacterTables(t *testing.T) {
	tables := []struct {
		name string
		ct   *CharacterTable
		dims []int
	}{
		{"C4", CharacterTableCyclic(4), []int{1, 1, 1, 1}},
		{"V4", CharacterTableKleinFour(), []int{1, 1, 1, 1}},
		{"D3", CharacterTableDihedral(3), []int{1, 1, 2}},
		{"D4", CharacterTableDihedral(4), []int{1, 1, 1, 1, 2}},
		{"D5", CharacterTableDihedral(5), []int{1, 1, 2, 2}},
		{"D6", CharacterTableDihedral(6), []int{1, 1, 1, 1, 2, 2}},
		{"S3", CharacterTableSymmetric(3), []int{1, 1, 2}},
		{"S4", CharacterTableSymmetric(4), []int{1, 1, 2, 3, 3}},
		{"Q8", CharacterTableQuaternion(), []int{1, 1, 1, 1, 2}},
	}
	for _, tc := range tables {
		t.Run(tc.name, func(t *testing.T) {
			ct := tc.ct
			if !ct.IsComplete() {
				t.Errorf("%s: table not complete (Σd² = %d, |G| = %d)",
					tc.name, ct.SumOfSquaresOfDims(), ct.Group().Order())
			}
			if got := ct.Dimensions(); !equalInts(got, tc.dims) {
				t.Errorf("%s: dims = %v, want %v", tc.name, got, tc.dims)
			}
			if !ct.RowOrthogonality(1e-7) {
				t.Errorf("%s: row orthogonality fails", tc.name)
			}
			if !ct.ColumnOrthogonality(1e-7) {
				t.Errorf("%s: column orthogonality fails", tc.name)
			}
			if ct.SumOfSquaresOfDims() != ct.Group().Order() {
				t.Errorf("%s: Σd² = %d, want %d", tc.name,
					ct.SumOfSquaresOfDims(), ct.Group().Order())
			}
		})
	}
}

func TestRegularDecomposition(t *testing.T) {
	// The regular representation contains each irreducible with multiplicity
	// equal to its degree.
	cases := []*CharacterTable{
		CharacterTableSymmetric(3),
		CharacterTableSymmetric(4),
		CharacterTableQuaternion(),
		CharacterTableDihedral(4),
	}
	for _, ct := range cases {
		reg := RegularCharacter(ct.Group())
		mult := ct.Decompose(reg)
		for i, m := range mult {
			if m != ct.Dimensions()[i] {
				t.Errorf("%s: irr %d multiplicity %d, want %d",
					ct.Group().Name(), i, m, ct.Dimensions()[i])
			}
		}
	}
}

func TestNaturalRepDecomposition(t *testing.T) {
	// The natural permutation rep of S_n is trivial ⊕ standard.
	for n := 3; n <= 4; n++ {
		ct := CharacterTableSymmetric(n)
		nat := NaturalRepSymmetric(n).Character()
		mult := ct.Decompose(nat)
		if mult[0] != 1 {
			t.Errorf("S%d: trivial multiplicity %d, want 1", n, mult[0])
		}
		total := 0
		for _, m := range mult {
			if m < 0 {
				t.Errorf("S%d: negative multiplicity %d", n, m)
			}
			total += m
		}
		// trivial + one (n-1)-dimensional standard = 2 constituents.
		if total != 2 {
			t.Errorf("S%d: total constituents %d, want 2", n, total)
		}
	}
}

func TestTensorCharacter(t *testing.T) {
	// χ_{V⊗W} = χ_V · χ_W.
	ct := CharacterTableSymmetric(4)
	sign := ct.Irreducible(1)
	std := ct.Irreducible(3)
	prod := TensorCharacters(sign, std)
	// standard ⊗ sign is the other 3-dimensional irreducible (index 4).
	other := ct.Irreducible(4)
	if !prod.ApproxEqual(other, 1e-7) {
		t.Errorf("sign⊗standard = %v, want %v", prod, other)
	}
}

func TestDualCharacter(t *testing.T) {
	// For C5 the dual of χ_k is χ_{5-k}; characters are complex conjugates.
	r := CyclicRep(5, 2)
	dual := r.Dual().Character()
	conj := ConjugateCharacter(r.Character())
	if !dual.ApproxEqual(conj, 1e-7) {
		t.Errorf("dual character != conjugate:\n%v\n%v", dual, conj)
	}
}

func TestFrobeniusReciprocity(t *testing.T) {
	// H = rotation subgroup C4 embeds in G = D4 via the identity index map on
	// rotations 0..3.
	G := DihedralGroup(4)
	H := CyclicGroup(4)
	emb := []int{0, 1, 2, 3}

	ctG := CharacterTableDihedral(4)
	ctH := CharacterTableCyclic(4)

	for hi := 0; hi < ctH.NumIrreducibles(); hi++ {
		psi := ctH.Irreducible(hi)
		ind, err := InduceCharacter(G, H, emb, psi)
		if err != nil {
			t.Fatalf("InduceCharacter: %v", err)
		}
		for gi := 0; gi < ctG.NumIrreducibles(); gi++ {
			chi := ctG.Irreducible(gi)
			lhs := InnerProduct(G, ind, chi)   // 〈Ind ψ, χ〉_G
			res := RestrictCharacter(chi, emb) // Res χ to H
			rhs := InnerProduct(H, psi, res)   // 〈ψ, Res χ〉_H
			if cmplx.Abs(lhs-rhs) > 1e-7 {
				t.Errorf("Frobenius reciprocity fails for H-irr %d, G-irr %d: %v vs %v",
					hi, gi, lhs, rhs)
			}
		}
	}
}

func TestInducedIsCharacter(t *testing.T) {
	G := DihedralGroup(4)
	H := CyclicGroup(4)
	emb := []int{0, 1, 2, 3}
	ctG := CharacterTableDihedral(4)
	ctH := CharacterTableCyclic(4)

	psi := ctH.Irreducible(1)
	ind, err := InduceCharacter(G, H, emb, psi)
	if err != nil {
		t.Fatalf("InduceCharacter: %v", err)
	}
	if !IsCharacter(G, ind, ctG.Irreducibles(), 1e-7) {
		t.Errorf("induced character is not a genuine character")
	}
	// Induced degree = [G:H]·deg(psi) = 2·1 = 2.
	if d := CharacterDimension(ind); d != 2 {
		t.Errorf("induced degree = %d, want 2", d)
	}
}

func TestRootOfUnity(t *testing.T) {
	if !ApproxEqualC(RootOfUnity(4, 1), complex(0, 1), tol) {
		t.Errorf("RootOfUnity(4,1) = %v, want i", RootOfUnity(4, 1))
	}
	if !ApproxEqualC(RootOfUnity(2, 1), complex(-1, 0), tol) {
		t.Errorf("RootOfUnity(2,1) = %v, want -1", RootOfUnity(2, 1))
	}
	// Sum of all n-th roots of unity is 0.
	var s complex128
	for k := 0; k < 6; k++ {
		s += RootOfUnity(6, k)
	}
	if cmplx.Abs(s) > tol {
		t.Errorf("sum of 6th roots = %v, want 0", s)
	}
}

func TestDihedralRep2DCharacter(t *testing.T) {
	// χ(r^b) = 2cos(2πhb/n) and χ(reflection) = 0.
	n, h := 4, 1
	r := DihedralRep2D(n, h)
	ch := r.Character()
	for b := 0; b < n; b++ {
		want := 2 * math.Cos(2*math.Pi*float64(h)*float64(b)/float64(n))
		if !ApproxEqualC(ch[b], complex(want, 0), 1e-7) {
			t.Errorf("χ(r^%d) = %v, want %v", b, ch[b], want)
		}
		// Reflections have index n+b.
		if !ApproxEqualC(ch[n+b], 0, 1e-7) {
			t.Errorf("χ(reflection %d) = %v, want 0", b, ch[n+b])
		}
	}
}

func TestPermutationMatrix(t *testing.T) {
	p := []int{2, 0, 1}
	m := PermutationMatrix(p)
	// e_0 ↦ e_2.
	col0 := m.Col(0)
	if !ApproxEqualC(col0[2], 1, tol) {
		t.Errorf("PermutationMatrix column 0 = %v, want e_2", col0)
	}
	if !m.IsUnitary(tol) {
		t.Errorf("permutation matrix should be unitary")
	}
	if !ApproxEqualC(m.Det()*m.Det(), 1, tol) {
		t.Errorf("permutation matrix det² = %v, want 1", m.Det()*m.Det())
	}
}

func TestDirectProductOrder(t *testing.T) {
	g := DirectProduct(CyclicGroup(2), CyclicGroup(3))
	if g.Order() != 6 {
		t.Fatalf("|C2×C3| = %d, want 6", g.Order())
	}
	// C2×C3 ≅ C6 is cyclic, hence abelian with an element of order 6.
	if !g.IsAbelian() {
		t.Errorf("C2×C3 should be abelian")
	}
	maxOrder := 0
	for i := 0; i < g.Order(); i++ {
		if o := g.ElementOrder(i); o > maxOrder {
			maxOrder = o
		}
	}
	if maxOrder != 6 {
		t.Errorf("max element order = %d, want 6", maxOrder)
	}
}

func equalInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
