package stochastic

import (
	"math"
	"math/rand"
	"sort"
)

// PoissonProcessCount returns the number of events of a homogeneous Poisson
// process of the given rate observed on the interval [0, T]. It has a Poisson
// distribution with mean rate*T.
func PoissonProcessCount(rng *rand.Rand, rate, T float64) int {
	if rate <= 0 || T <= 0 {
		return 0
	}
	return PoissonSample(rng, rate*T)
}

// PoissonArrivals returns the ordered arrival times of a homogeneous Poisson
// process of the given rate on the interval [0, T]. Arrivals are generated by
// accumulating exponential inter-arrival times.
func PoissonArrivals(rng *rand.Rand, rate, T float64) []float64 {
	var arr []float64
	if rate <= 0 || T <= 0 {
		return arr
	}
	t := 0.0
	for {
		t += ExponentialSample(rng, rate)
		if t > T {
			break
		}
		arr = append(arr, t)
	}
	return arr
}

// PoissonArrivalsN returns the first n arrival times of a homogeneous Poisson
// process of the given rate, starting from time 0.
func PoissonArrivalsN(rng *rand.Rand, rate float64, n int) []float64 {
	if n <= 0 || rate <= 0 {
		return nil
	}
	arr := make([]float64, n)
	t := 0.0
	for i := 0; i < n; i++ {
		t += ExponentialSample(rng, rate)
		arr[i] = t
	}
	return arr
}

// InterArrivalTimes returns n independent exponential inter-arrival times of a
// Poisson process with the given rate.
func InterArrivalTimes(rng *rand.Rand, rate float64, n int) []float64 {
	return ExponentialVector(rng, n, rate)
}

// ArrivalsToInterArrivals converts a sorted slice of arrival times into the
// gaps between successive arrivals (the first gap is measured from time 0).
func ArrivalsToInterArrivals(arrivals []float64) []float64 {
	if len(arrivals) == 0 {
		return nil
	}
	out := make([]float64, len(arrivals))
	prev := 0.0
	for i, a := range arrivals {
		out[i] = a - prev
		prev = a
	}
	return out
}

// CountingPath returns the counting process N(t) of the given sorted arrival
// times sampled on a regular grid of nSteps+1 points over [0, T]. N(t) is the
// number of arrivals at or before time t.
func CountingPath(arrivals []float64, T float64, nSteps int) Path {
	if nSteps < 1 {
		nSteps = 1
	}
	dt := T / float64(nSteps)
	times := make([]float64, nSteps+1)
	vals := make([]float64, nSteps+1)
	for i := 0; i <= nSteps; i++ {
		t := float64(i) * dt
		times[i] = t
		vals[i] = float64(countLE(arrivals, t))
	}
	return Path{Times: times, Values: vals}
}

// PoissonCountingProcess simulates a homogeneous Poisson process of the given
// rate on [0, T] and returns its counting path sampled on nSteps+1 grid points.
func PoissonCountingProcess(rng *rand.Rand, rate, T float64, nSteps int) Path {
	arr := PoissonArrivals(rng, rate, T)
	return CountingPath(arr, T, nSteps)
}

// countLE returns the number of elements of the sorted slice that are <= t.
func countLE(sorted []float64, t float64) int {
	return sort.Search(len(sorted), func(i int) bool { return sorted[i] > t })
}

// ThinnedPoisson returns the sub-sequence of arrivals kept when each arrival is
// retained independently with probability p (Poisson thinning).
func ThinnedPoisson(rng *rand.Rand, arrivals []float64, p float64) []float64 {
	var out []float64
	for _, a := range arrivals {
		if BernoulliSample(rng, p) {
			out = append(out, a)
		}
	}
	return out
}

// SuperposedPoisson merges two sorted arrival sequences into a single sorted
// sequence. The superposition of independent Poisson processes with rates r1
// and r2 is a Poisson process with rate r1+r2.
func SuperposedPoisson(a, b []float64) []float64 {
	out := make([]float64, 0, len(a)+len(b))
	i, j := 0, 0
	for i < len(a) && j < len(b) {
		if a[i] <= b[j] {
			out = append(out, a[i])
			i++
		} else {
			out = append(out, b[j])
			j++
		}
	}
	out = append(out, a[i:]...)
	out = append(out, b[j:]...)
	return out
}

// InhomogeneousPoissonArrivals returns the arrival times of an inhomogeneous
// Poisson process on [0, T] whose intensity is the function lambda(t), using
// Lewis-Shedler thinning. The argument maxRate must be an upper bound of
// lambda over [0, T].
func InhomogeneousPoissonArrivals(rng *rand.Rand, lambda func(float64) float64, maxRate, T float64) []float64 {
	var arr []float64
	if maxRate <= 0 || T <= 0 {
		return arr
	}
	t := 0.0
	for {
		t += ExponentialSample(rng, maxRate)
		if t > T {
			break
		}
		if rng.Float64() <= lambda(t)/maxRate {
			arr = append(arr, t)
		}
	}
	return arr
}

// CompoundPoisson returns the value X(T) = sum of jumps of a compound Poisson
// process with the given event rate on [0, T], where each jump is drawn from
// jump(rng).
func CompoundPoisson(rng *rand.Rand, rate, T float64, jump func(*rand.Rand) float64) float64 {
	n := PoissonProcessCount(rng, rate, T)
	s := 0.0
	for i := 0; i < n; i++ {
		s += jump(rng)
	}
	return s
}

// CompoundPoissonPath returns the piecewise-constant sample path of a compound
// Poisson process on [0, T] sampled on nSteps+1 grid points. Jumps occur at the
// Poisson arrival times with sizes drawn from jump(rng).
func CompoundPoissonPath(rng *rand.Rand, rate, T float64, nSteps int, jump func(*rand.Rand) float64) Path {
	if nSteps < 1 {
		nSteps = 1
	}
	arrivals := PoissonArrivals(rng, rate, T)
	sizes := make([]float64, len(arrivals))
	cum := make([]float64, len(arrivals))
	acc := 0.0
	for i := range arrivals {
		sizes[i] = jump(rng)
		acc += sizes[i]
		cum[i] = acc
	}
	dt := T / float64(nSteps)
	times := make([]float64, nSteps+1)
	vals := make([]float64, nSteps+1)
	for i := 0; i <= nSteps; i++ {
		t := float64(i) * dt
		times[i] = t
		k := countLE(arrivals, t)
		if k == 0 {
			vals[i] = 0
		} else {
			vals[i] = cum[k-1]
		}
	}
	return Path{Times: times, Values: vals}
}

// CompoundPoissonMean returns the analytic mean rate*T*E[jump] of a compound
// Poisson process observed on [0, T], given the mean jump size.
func CompoundPoissonMean(rate, T, jumpMean float64) float64 {
	return rate * T * jumpMean
}

// CompoundPoissonVariance returns the analytic variance rate*T*E[jump^2] of a
// compound Poisson process on [0, T], given the mean and variance of the jump
// distribution (E[jump^2] = jumpVar + jumpMean^2).
func CompoundPoissonVariance(rate, T, jumpMean, jumpVar float64) float64 {
	return rate * T * (jumpVar + jumpMean*jumpMean)
}

// PoissonPMF returns the probability mass P(N = k) for a Poisson distribution
// with mean lambda.
func PoissonPMF(k int, lambda float64) float64 {
	if k < 0 || lambda < 0 {
		return 0
	}
	lg, _ := math.Lgamma(float64(k) + 1)
	return math.Exp(float64(k)*math.Log(lambda) - lambda - lg)
}

// PoissonCDF returns the cumulative probability P(N <= k) for a Poisson
// distribution with mean lambda.
func PoissonCDF(k int, lambda float64) float64 {
	if k < 0 {
		return 0
	}
	s := 0.0
	for i := 0; i <= k; i++ {
		s += PoissonPMF(i, lambda)
	}
	if s > 1 {
		s = 1
	}
	return s
}
