package infogeom

import "math"

// BregmanGenerator describes a strictly convex, differentiable potential
// function F on R^n together with its gradient. It induces a Bregman
// divergence and, through the Legendre transform, a pair of dual coordinate
// systems central to the dually flat geometry of exponential families.
type BregmanGenerator struct {
	// F evaluates the convex potential at a point.
	F func(x []float64) float64
	// Grad returns the gradient of F at a point.
	Grad func(x []float64) []float64
}

// BregmanDivergence returns the Bregman divergence generated by gen,
//
//	D_F(x, y) = F(x) - F(y) - <grad F(y), x - y>,
//
// which is non-negative for a convex generator and zero iff x == y. It returns
// ErrDim when x and y have different lengths.
func BregmanDivergence(gen BregmanGenerator, x, y []float64) (float64, error) {
	if len(x) != len(y) || len(x) == 0 {
		return 0, ErrDim
	}
	g := gen.Grad(y)
	if len(g) != len(x) {
		return 0, ErrDim
	}
	diff, err := SubVectors(x, y)
	if err != nil {
		return 0, err
	}
	inner, err := Dot(g, diff)
	if err != nil {
		return 0, err
	}
	return gen.F(x) - gen.F(y) - inner, nil
}

// SquaredEuclideanGenerator returns the Bregman generator F(x) = 1/2 |x|^2
// whose divergence is one half the squared Euclidean distance.
func SquaredEuclideanGenerator() BregmanGenerator {
	return BregmanGenerator{
		F: func(x []float64) float64 {
			var s float64
			for _, xi := range x {
				s += xi * xi
			}
			return 0.5 * s
		},
		Grad: func(x []float64) []float64 {
			return CloneVector(x)
		},
	}
}

// SquaredEuclideanDivergence returns 1/2 |x-y|^2, the Bregman divergence of the
// squared-norm generator.
func SquaredEuclideanDivergence(x, y []float64) (float64, error) {
	if len(x) != len(y) || len(x) == 0 {
		return 0, ErrDim
	}
	var s float64
	for i := range x {
		d := x[i] - y[i]
		s += d * d
	}
	return 0.5 * s, nil
}

// NegativeEntropyGenerator returns the Bregman generator
// F(x) = sum x_i (ln x_i - 1) on the positive orthant, whose divergence is the
// generalised Kullback-Leibler (I-) divergence.
func NegativeEntropyGenerator() BregmanGenerator {
	return BregmanGenerator{
		F: func(x []float64) float64 {
			var s float64
			for _, xi := range x {
				if xi > 0 {
					s += xi*math.Log(xi) - xi
				}
			}
			return s
		},
		Grad: func(x []float64) []float64 {
			g := make([]float64, len(x))
			for i, xi := range x {
				if xi > 0 {
					g[i] = math.Log(xi)
				} else {
					g[i] = math.Inf(-1)
				}
			}
			return g
		},
	}
}

// GeneralizedKLDivergence returns the generalised Kullback-Leibler (I-)
// divergence between non-negative vectors,
//
//	sum ( x_i ln(x_i/y_i) - x_i + y_i ),
//
// the Bregman divergence of the negative-entropy generator. For inputs that
// are probability distributions the trailing terms cancel and this reduces to
// the ordinary KL divergence. It returns math.Inf(1) when y_i = 0 < x_i.
func GeneralizedKLDivergence(x, y []float64) (float64, error) {
	if len(x) != len(y) || len(x) == 0 {
		return 0, ErrDim
	}
	var s float64
	for i := range x {
		if x[i] < 0 || y[i] < 0 {
			return 0, ErrDomain
		}
		if x[i] > 0 {
			if y[i] <= 0 {
				return math.Inf(1), nil
			}
			s += x[i]*math.Log(x[i]/y[i]) - x[i] + y[i]
		} else {
			s += y[i]
		}
	}
	return s, nil
}

// ItakuraSaitoGenerator returns the Bregman generator
// F(x) = -sum ln x_i on the positive orthant, whose divergence is the
// Itakura-Saito divergence used in spectral signal processing.
func ItakuraSaitoGenerator() BregmanGenerator {
	return BregmanGenerator{
		F: func(x []float64) float64 {
			var s float64
			for _, xi := range x {
				s -= math.Log(xi)
			}
			return s
		},
		Grad: func(x []float64) []float64 {
			g := make([]float64, len(x))
			for i, xi := range x {
				g[i] = -1 / xi
			}
			return g
		},
	}
}

// ItakuraSaitoDivergence returns the Itakura-Saito divergence between positive
// vectors, sum ( x_i/y_i - ln(x_i/y_i) - 1 ). It returns ErrDomain when any
// entry is non-positive.
func ItakuraSaitoDivergence(x, y []float64) (float64, error) {
	if len(x) != len(y) || len(x) == 0 {
		return 0, ErrDim
	}
	var s float64
	for i := range x {
		if x[i] <= 0 || y[i] <= 0 {
			return 0, ErrDomain
		}
		r := x[i] / y[i]
		s += r - math.Log(r) - 1
	}
	return s, nil
}

// MahalanobisDivergence returns the Bregman divergence generated by the
// quadratic potential F(x) = 1/2 x^T A x for a symmetric positive-definite
// matrix A, namely 1/2 (x-y)^T A (x-y). It returns ErrDim on a shape mismatch.
func MahalanobisDivergence(a [][]float64, x, y []float64) (float64, error) {
	diff, err := SubVectors(x, y)
	if err != nil {
		return 0, err
	}
	q, err := QuadraticForm(a, diff)
	if err != nil {
		return 0, err
	}
	return 0.5 * q, nil
}

// DualCoordinates returns the dual (eta) coordinates grad F(theta) of the
// primal (theta) coordinates under the generator gen. For an exponential
// family whose potential is the log-partition function this maps natural
// parameters to expectation parameters.
func DualCoordinates(gen BregmanGenerator, theta []float64) []float64 {
	return gen.Grad(theta)
}

// BregmanCentroid returns the right-sided Bregman centroid of the points, which
// for every Bregman divergence coincides with the arithmetic mean
// (1/m) sum x_j and minimises sum_j D_F(x_j, c) over c. It returns ErrDim when
// the point set is empty or ragged.
func BregmanCentroid(points [][]float64) ([]float64, error) {
	if len(points) == 0 {
		return nil, ErrDim
	}
	n := len(points[0])
	if n == 0 {
		return nil, ErrDim
	}
	c := make([]float64, n)
	for _, p := range points {
		if len(p) != n {
			return nil, ErrDim
		}
		for i := range p {
			c[i] += p[i]
		}
	}
	inv := 1 / float64(len(points))
	for i := range c {
		c[i] *= inv
	}
	return c, nil
}
