// Package infogeom implements tools from information geometry, the study of
// probability distributions as points on differentiable (statistical)
// manifolds equipped with the Fisher-Rao metric and the family of
// alpha-connections.
//
// The package is organised around a handful of concrete concerns:
//
//   - divergences between discrete probability distributions represented as
//     plain []float64 slices whose entries are non-negative and sum to one:
//     the Kullback-Leibler, Jensen-Shannon, Renyi, Tsallis, chi-squared,
//     Hellinger, total-variation, Bhattacharyya and general f-divergences,
//     together with the Amari alpha-divergence family;
//
//   - Bregman divergences generated by a strictly convex potential, of which
//     squared Euclidean distance, the (generalised) KL divergence and the
//     Itakura-Saito divergence are special cases, plus the associated
//     Legendre duality between primal and dual coordinates;
//
//   - the Fisher information matrix for exponential families, obtained as the
//     Hessian of the log-partition (cumulant) function or equivalently as the
//     covariance of the sufficient statistics, with closed forms for the
//     Bernoulli, categorical, Poisson, exponential and Gaussian families;
//
//   - the Fisher-Rao geodesic distance on statistical manifolds, in closed
//     form for the Bernoulli and categorical (multinomial) simplex — which is
//     isometric to a sphere via the square-root embedding — and for the
//     location-scale Gaussian family, whose Fisher-Rao geometry is that of the
//     hyperbolic plane;
//
//   - exponential-family cumulant and expectation maps, the dual e-/m-
//     (natural / expectation) coordinate systems related by the Legendre
//     transform of the log-partition function, and the alpha-connections and
//     alpha-representations of Amari and Nagaoka;
//
//   - natural-gradient descent, in which an ordinary Euclidean gradient is
//     preconditioned by the inverse Fisher information matrix so that updates
//     follow the steepest-descent direction of the underlying manifold.
//
// Unless documented otherwise all logarithmic quantities are expressed in
// nats (natural logarithms); helpers suffixed "Bits" report the same quantity
// in bits. Vectors are []float64 and matrices are row-major [][]float64.
//
// Every routine validates the shape and (where relevant) the normalisation of
// its arguments and reports a sentinel error rather than panicking on
// malformed input. The package depends only on the Go standard library.
package infogeom
