package liealgebra

// SimpleRoots returns the simple roots of a classical type (A, B, C or D) as
// Euclidean coordinate vectors. Type A_n lives in R^(n+1) with α_i = e_i-e_{i+1};
// types B_n, C_n and D_n live in R^n. It returns [ErrType] for exceptional types
// (use [PositiveRootLabels] for those).
func SimpleRoots(family string, rank int) ([][]float64, error) {
	f, err := normFamily(family)
	if err != nil {
		return nil, err
	}
	if err := validRank(f, rank); err != nil {
		return nil, err
	}
	n := rank
	switch f {
	case "A":
		roots := make([][]float64, n)
		for i := 0; i < n; i++ {
			v := make([]float64, n+1)
			v[i] = 1
			v[i+1] = -1
			roots[i] = v
		}
		return roots, nil
	case "B":
		roots := make([][]float64, n)
		for i := 0; i < n-1; i++ {
			v := make([]float64, n)
			v[i] = 1
			v[i+1] = -1
			roots[i] = v
		}
		last := make([]float64, n)
		last[n-1] = 1 // short root e_n
		roots[n-1] = last
		return roots, nil
	case "C":
		roots := make([][]float64, n)
		for i := 0; i < n-1; i++ {
			v := make([]float64, n)
			v[i] = 1
			v[i+1] = -1
			roots[i] = v
		}
		last := make([]float64, n)
		last[n-1] = 2 // long root 2 e_n
		roots[n-1] = last
		return roots, nil
	case "D":
		roots := make([][]float64, n)
		for i := 0; i < n-1; i++ {
			v := make([]float64, n)
			v[i] = 1
			v[i+1] = -1
			roots[i] = v
		}
		last := make([]float64, n)
		last[n-2] = 1
		last[n-1] = 1 // e_{n-1}+e_n
		roots[n-1] = last
		return roots, nil
	}
	return nil, ErrType
}

// PositiveRoots returns the positive roots of a classical type as Euclidean
// coordinate vectors. It returns [ErrType] for exceptional types.
func PositiveRoots(family string, rank int) ([][]float64, error) {
	f, err := normFamily(family)
	if err != nil {
		return nil, err
	}
	if err := validRank(f, rank); err != nil {
		return nil, err
	}
	n := rank
	var roots [][]float64
	e := func(dim, i int, s float64) []float64 {
		v := make([]float64, dim)
		v[i] = s
		return v
	}
	switch f {
	case "A":
		dim := n + 1
		for i := 0; i < dim; i++ {
			for j := i + 1; j < dim; j++ {
				v := make([]float64, dim)
				v[i] = 1
				v[j] = -1
				roots = append(roots, v)
			}
		}
	case "B":
		for i := 0; i < n; i++ {
			for j := i + 1; j < n; j++ {
				a := make([]float64, n)
				a[i], a[j] = 1, -1 // e_i - e_j
				roots = append(roots, a)
				b := make([]float64, n)
				b[i], b[j] = 1, 1 // e_i + e_j
				roots = append(roots, b)
			}
			roots = append(roots, e(n, i, 1)) // e_i
		}
	case "C":
		for i := 0; i < n; i++ {
			for j := i + 1; j < n; j++ {
				a := make([]float64, n)
				a[i], a[j] = 1, -1
				roots = append(roots, a)
				b := make([]float64, n)
				b[i], b[j] = 1, 1
				roots = append(roots, b)
			}
			roots = append(roots, e(n, i, 2)) // 2 e_i
		}
	case "D":
		for i := 0; i < n; i++ {
			for j := i + 1; j < n; j++ {
				a := make([]float64, n)
				a[i], a[j] = 1, -1
				roots = append(roots, a)
				b := make([]float64, n)
				b[i], b[j] = 1, 1
				roots = append(roots, b)
			}
		}
	default:
		return nil, ErrType
	}
	return roots, nil
}

// AllRoots returns all roots (positive together with their negatives) of a
// classical type as Euclidean coordinate vectors.
func AllRoots(family string, rank int) ([][]float64, error) {
	pos, err := PositiveRoots(family, rank)
	if err != nil {
		return nil, err
	}
	out := make([][]float64, 0, 2*len(pos))
	out = append(out, pos...)
	for _, r := range pos {
		out = append(out, VecScale(r, -1))
	}
	return out, nil
}

// CartanMatrixFromRoots builds the Cartan matrix A[i][j] = 2(α_i,α_j)/(α_j,α_j)
// from a list of simple roots given as Euclidean coordinate vectors. It returns
// [ErrDim] if any root is zero or the coordinate lengths disagree.
func CartanMatrixFromRoots(simple [][]float64) (*Matrix, error) {
	n := len(simple)
	if n == 0 {
		return NewMatrix(0, 0), nil
	}
	dim := len(simple[0])
	for _, r := range simple {
		if len(r) != dim {
			return nil, ErrDim
		}
	}
	m := NewMatrix(n, n)
	for i := 0; i < n; i++ {
		for j := 0; j < n; j++ {
			ai, _ := VecDot(simple[i], simple[j])
			ajj := VecNormSquared(simple[j])
			if ajj == 0 {
				return nil, ErrDim
			}
			m.Data[i*n+j] = 2 * ai / ajj
		}
	}
	return m, nil
}

// WeylOrbit returns the orbit of a Euclidean vector v under the Weyl group
// generated by reflections in the given simple roots. It repeatedly applies all
// simple reflections until the orbit stabilises (finite for a genuine root
// system) and returns the distinct vectors within tolerance tol.
func WeylOrbit(simple [][]float64, v []float64, tol float64) ([][]float64, error) {
	if len(simple) == 0 {
		return [][]float64{append([]float64(nil), v...)}, nil
	}
	orbit := [][]float64{append([]float64(nil), v...)}
	contains := func(x []float64) bool {
		for _, o := range orbit {
			if VecEqual(o, x, tol) {
				return true
			}
		}
		return false
	}
	changed := true
	for changed {
		changed = false
		for idx := 0; idx < len(orbit); idx++ {
			for _, s := range simple {
				r, err := WeylReflection(s, orbit[idx])
				if err != nil {
					return nil, err
				}
				if !contains(r) {
					orbit = append(orbit, r)
					changed = true
				}
			}
		}
	}
	return orbit, nil
}
