package groups

import "sort"

// FiniteGroup is an abstract finite group whose elements are the integer
// indices 0, 1, ..., Order()-1 and whose binary operation is supplied as a
// function on those indices. It supports Cayley-table generation, element and
// group orders, subgroup and coset enumeration, and structural tests such as
// abelian/cyclic detection.
type FiniteGroup struct {
	n        int
	identity int
	op       func(a, b int) int
}

// NewFiniteGroup builds a FiniteGroup on the elements {0, ..., n-1} with the
// given operation and identity index. The operation must return an index in
// [0, n) for every pair of arguments. n must be positive and identity must be
// a valid index. Use [FiniteGroup.IsValid] to check the closure, associativity
// and inverse axioms of the resulting structure.
func NewFiniteGroup(n, identity int, op func(a, b int) int) *FiniteGroup {
	if n <= 0 {
		panic("groups: NewFiniteGroup requires n > 0")
	}
	if identity < 0 || identity >= n {
		panic("groups: NewFiniteGroup identity out of range")
	}
	return &FiniteGroup{n: n, identity: identity, op: op}
}

// Order returns the number of elements in the group.
func (g *FiniteGroup) Order() int {
	return g.n
}

// Op returns the product a·b of two element indices under the group operation.
func (g *FiniteGroup) Op(a, b int) int {
	return g.op(a, b)
}

// Identity returns the index of the group's identity element.
func (g *FiniteGroup) Identity() int {
	return g.identity
}

// Elements returns the slice {0, 1, ..., Order()-1} of all element indices.
func (g *FiniteGroup) Elements() []int {
	e := make([]int, g.n)
	for i := range e {
		e[i] = i
	}
	return e
}

// CayleyTable returns the group's multiplication table as an n×n matrix where
// entry [a][b] holds the index of a·b.
func (g *FiniteGroup) CayleyTable() [][]int {
	t := make([][]int, g.n)
	for a := 0; a < g.n; a++ {
		row := make([]int, g.n)
		for b := 0; b < g.n; b++ {
			row[b] = g.op(a, b)
		}
		t[a] = row
	}
	return t
}

// Inverse returns the index of the inverse of a. It panics if a has no inverse
// (which cannot happen in a valid group). The argument a must be a valid
// index.
func (g *FiniteGroup) Inverse(a int) int {
	for b := 0; b < g.n; b++ {
		if g.op(a, b) == g.identity && g.op(b, a) == g.identity {
			return b
		}
	}
	panic("groups: Inverse: element has no inverse (not a group)")
}

// ElementOrder returns the order of a: the smallest k > 0 with a^k equal to the
// identity. The argument a must be a valid index.
func (g *FiniteGroup) ElementOrder(a int) int {
	cur := a
	k := 1
	for cur != g.identity {
		cur = g.op(cur, a)
		k++
		if k > g.n {
			panic("groups: ElementOrder: element does not return to identity (not a group)")
		}
	}
	return k
}

// IsAbelian reports whether the group is commutative: a·b == b·a for every
// pair of elements.
func (g *FiniteGroup) IsAbelian() bool {
	for a := 0; a < g.n; a++ {
		for b := a + 1; b < g.n; b++ {
			if g.op(a, b) != g.op(b, a) {
				return false
			}
		}
	}
	return true
}

// IsCyclic reports whether the group is cyclic, i.e. some single element
// generates all n elements.
func (g *FiniteGroup) IsCyclic() bool {
	for a := 0; a < g.n; a++ {
		if g.ElementOrder(a) == g.n {
			return true
		}
	}
	return g.n == 1
}

// Center returns the sorted indices of the center Z(G): the elements that
// commute with every element of the group.
func (g *FiniteGroup) Center() []int {
	var center []int
	for a := 0; a < g.n; a++ {
		central := true
		for b := 0; b < g.n; b++ {
			if g.op(a, b) != g.op(b, a) {
				central = false
				break
			}
		}
		if central {
			center = append(center, a)
		}
	}
	return center
}

// GeneratedSubgroup returns the sorted set of elements of the subgroup
// generated by the given generators, computed by closing the generator set
// under the group operation. An empty generator list yields the trivial
// subgroup {identity}.
func (g *FiniteGroup) GeneratedSubgroup(gens []int) []int {
	inSet := make([]bool, g.n)
	inSet[g.identity] = true
	frontier := []int{g.identity}
	for _, x := range gens {
		if !inSet[x] {
			inSet[x] = true
			frontier = append(frontier, x)
		}
	}
	// Repeatedly multiply known elements together until closure.
	for changed := true; changed; {
		changed = false
		known := frontier
		for _, a := range known {
			for _, x := range gens {
				p := g.op(a, x)
				if !inSet[p] {
					inSet[p] = true
					frontier = append(frontier, p)
					changed = true
				}
			}
		}
	}
	var result []int
	for i, ok := range inSet {
		if ok {
			result = append(result, i)
		}
	}
	sort.Ints(result)
	return result
}

// IsSubgroup reports whether the given set of element indices forms a subgroup:
// it must be non-empty, contain the identity, and be closed under the operation
// and under inverses. Duplicate entries are tolerated.
func (g *FiniteGroup) IsSubgroup(elems []int) bool {
	if len(elems) == 0 {
		return false
	}
	inSet := make([]bool, g.n)
	var uniq []int
	for _, e := range elems {
		if e < 0 || e >= g.n {
			return false
		}
		if !inSet[e] {
			inSet[e] = true
			uniq = append(uniq, e)
		}
	}
	if !inSet[g.identity] {
		return false
	}
	for _, a := range uniq {
		if !inSet[g.Inverse(a)] {
			return false
		}
		for _, b := range uniq {
			if !inSet[g.op(a, b)] {
				return false
			}
		}
	}
	return true
}

// LeftCoset returns the sorted left coset g·H = {g·h : h in subgroup} for the
// element index x. The subgroup argument is treated as a set of indices.
func (g *FiniteGroup) LeftCoset(subgroup []int, x int) []int {
	return g.groupsCoset(subgroup, x, true)
}

// RightCoset returns the sorted right coset H·g = {h·g : h in subgroup} for the
// element index x.
func (g *FiniteGroup) RightCoset(subgroup []int, x int) []int {
	return g.groupsCoset(subgroup, x, false)
}

// groupsCoset computes a left (left==true) or right coset of the subgroup.
func (g *FiniteGroup) groupsCoset(subgroup []int, x int, left bool) []int {
	seen := make([]bool, g.n)
	var out []int
	for _, h := range subgroup {
		var p int
		if left {
			p = g.op(x, h)
		} else {
			p = g.op(h, x)
		}
		if !seen[p] {
			seen[p] = true
			out = append(out, p)
		}
	}
	sort.Ints(out)
	return out
}

// Cosets returns the partition of the group into distinct left cosets of the
// given subgroup, each coset sorted and the cosets ordered by their smallest
// element. By Lagrange's theorem these cosets have equal size and partition the
// group.
func (g *FiniteGroup) Cosets(subgroup []int) [][]int {
	covered := make([]bool, g.n)
	var cosets [][]int
	for x := 0; x < g.n; x++ {
		if covered[x] {
			continue
		}
		coset := g.LeftCoset(subgroup, x)
		for _, e := range coset {
			covered[e] = true
		}
		cosets = append(cosets, coset)
	}
	return cosets
}

// Index returns the index [G:H] of the subgroup H in the group G, the number of
// distinct left cosets. For a valid subgroup this equals |G|/|H|.
func (g *FiniteGroup) Index(subgroup []int) int {
	return len(g.Cosets(subgroup))
}

// IsValid reports whether the structure satisfies the group axioms over its n
// indices: closure, the declared identity acting as a two-sided identity,
// existence of inverses, and associativity. This is an O(n^3) check intended
// for validating hand-built tables.
func (g *FiniteGroup) IsValid() bool {
	// Closure and identity.
	for a := 0; a < g.n; a++ {
		if g.op(g.identity, a) != a || g.op(a, g.identity) != a {
			return false
		}
		for b := 0; b < g.n; b++ {
			p := g.op(a, b)
			if p < 0 || p >= g.n {
				return false
			}
		}
	}
	// Inverses.
	for a := 0; a < g.n; a++ {
		found := false
		for b := 0; b < g.n; b++ {
			if g.op(a, b) == g.identity && g.op(b, a) == g.identity {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	// Associativity.
	for a := 0; a < g.n; a++ {
		for b := 0; b < g.n; b++ {
			for c := 0; c < g.n; c++ {
				if g.op(g.op(a, b), c) != g.op(a, g.op(b, c)) {
					return false
				}
			}
		}
	}
	return true
}

// CyclicGroupZn returns the additive cyclic group Z/nZ as a FiniteGroup: the
// elements are 0..n-1, the operation is addition modulo n, and the identity is
// 0. The argument n must be positive.
func CyclicGroupZn(n int) *FiniteGroup {
	if n <= 0 {
		panic("groups: CyclicGroupZn requires n > 0")
	}
	return NewFiniteGroup(n, 0, func(a, b int) int {
		return (a + b) % n
	})
}

// SymmetricGroupTable returns the symmetric group S_n as a FiniteGroup whose
// element indices enumerate the permutations in the lexicographic order of
// [SymmetricGroup]. The operation composes permutations and the identity is
// index 0. n must be non-negative and small. Use [SymmetricGroup] to recover
// the permutation for a given index.
func SymmetricGroupTable(n int) *FiniteGroup {
	perms := SymmetricGroup(n)
	index := make(map[string]int, len(perms))
	for i, p := range perms {
		index[groupsPermKey(p)] = i
	}
	op := func(a, b int) int {
		return index[groupsPermKey(Compose(perms[a], perms[b]))]
	}
	return NewFiniteGroup(len(perms), 0, op)
}

// groupsPermKey returns a stable string key for a permutation.
func groupsPermKey(p Perm) string {
	b := make([]byte, 0, len(p)*2)
	for _, v := range p {
		b = append(b, byte(v>>8), byte(v))
	}
	return string(b)
}
