package groups

import "testing"

func TestCyclicGroupZn(t *testing.T) {
	g := CyclicGroupZn(6)
	if !g.IsValid() {
		t.Errorf("Z/6Z not valid")
	}
	if !g.IsAbelian() || !g.IsCyclic() {
		t.Errorf("Z/6Z should be abelian and cyclic")
	}
	// element orders match n/gcd(a,n)
	for a := 0; a < 6; a++ {
		if g.ElementOrder(a) != ElementOrderZn(a, 6) {
			t.Errorf("order mismatch for %d", a)
		}
	}
	if g.Inverse(2) != 4 {
		t.Errorf("inverse of 2 in Z/6 want 4")
	}
}

func TestCayleyTable(t *testing.T) {
	g := CyclicGroupZn(3)
	tbl := g.CayleyTable()
	want := [][]int{{0, 1, 2}, {1, 2, 0}, {2, 0, 1}}
	for i := range want {
		for j := range want[i] {
			if tbl[i][j] != want[i][j] {
				t.Errorf("CayleyTable[%d][%d]=%d want %d", i, j, tbl[i][j], want[i][j])
			}
		}
	}
}

func TestSubgroupsAndCosets(t *testing.T) {
	g := CyclicGroupZn(6)
	// subgroup generated by 2: {0,2,4}
	h := g.GeneratedSubgroup([]int{2})
	if len(h) != 3 || h[0] != 0 || h[1] != 2 || h[2] != 4 {
		t.Fatalf("<2> in Z/6 = %v want [0 2 4]", h)
	}
	if !g.IsSubgroup(h) {
		t.Errorf("{0,2,4} should be a subgroup")
	}
	if g.IsSubgroup([]int{0, 1}) {
		t.Errorf("{0,1} not a subgroup of Z/6")
	}
	// index [G:H] = 2, cosets partition group
	cosets := g.Cosets(h)
	if len(cosets) != 2 {
		t.Errorf("expected 2 cosets got %d", len(cosets))
	}
	if g.Index(h) != 2 {
		t.Errorf("index want 2")
	}
	// Lagrange: |H| divides |G|
	if g.Order()%len(h) != 0 {
		t.Errorf("Lagrange violated")
	}
	// left coset 1+H = {1,3,5}
	lc := g.LeftCoset(h, 1)
	if len(lc) != 3 || lc[0] != 1 || lc[1] != 3 || lc[2] != 5 {
		t.Errorf("1+H = %v want [1 3 5]", lc)
	}
}

func TestSymmetricGroupTable(t *testing.T) {
	g := SymmetricGroupTable(3)
	if g.Order() != 6 {
		t.Fatalf("|S_3|=%d want 6", g.Order())
	}
	if !g.IsValid() {
		t.Errorf("S_3 fails axioms")
	}
	if g.IsAbelian() {
		t.Errorf("S_3 is non-abelian")
	}
	if g.IsCyclic() {
		t.Errorf("S_3 is not cyclic")
	}
	// center of S_3 is trivial
	c := g.Center()
	if len(c) != 1 || c[0] != g.Identity() {
		t.Errorf("center of S_3 should be trivial got %v", c)
	}
	// A_3 subgroup has order 3
	perms := SymmetricGroup(3)
	var even []int
	for i, p := range perms {
		if p.Sign() == 1 {
			even = append(even, i)
		}
	}
	if !g.IsSubgroup(even) || len(even) != 3 {
		t.Errorf("A_3 should be an order-3 subgroup")
	}
	if g.Index(even) != 2 {
		t.Errorf("[S_3:A_3] want 2")
	}
}

func BenchmarkSymmetricGroupTableIsValid(b *testing.B) {
	// The heaviest routine: build S_4 (24 elements) and run the O(n^3)
	// associativity/axiom check.
	for i := 0; i < b.N; i++ {
		g := SymmetricGroupTable(4)
		if !g.IsValid() {
			b.Fatal("S_4 invalid")
		}
	}
}
