package operatortheory

import (
	"math"
	"math/cmplx"
)

// ScalarFunction is a complex-valued function of a complex variable, the kind of
// analytic function to which the functional calculus applies.
type ScalarFunction func(complex128) complex128

// ApplyFunction returns f(m) defined by the holomorphic functional calculus for
// a diagonalisable (in particular, normal) operator: if m = V diag(lambda)
// V^{-1} then f(m) = V diag(f(lambda)) V^{-1}. Hermitian matrices use the exact
// unitary eigendecomposition; other matrices use the eigenvectors from inverse
// iteration. It returns ErrNotSquare for a non-square matrix and ErrNotNormal
// when the eigenvectors are too ill-conditioned to invert (a defective matrix).
func (m *Matrix) ApplyFunction(f ScalarFunction) (*Matrix, error) {
	if !m.IsSquare() {
		return nil, ErrNotSquare
	}
	n := m.rows
	if n == 0 {
		return NewMatrix(0, 0), nil
	}
	if m.IsHermitian(1e-9) {
		vals, vecs := hermitianEigenRaw(m.HermitianPart())
		d := NewMatrix(n, n)
		for i, lam := range vals {
			d.data[i*n+i] = f(complex(lam, 0))
		}
		tmp, _ := vecs.Mul(d)
		return tmp.Mul(vecs.Adjoint())
	}
	pairs, err := m.Eigen()
	if err != nil {
		return nil, err
	}
	v := NewMatrix(n, n)
	for c := 0; c < n; c++ {
		for i := 0; i < n; i++ {
			v.data[i*n+c] = pairs[c].Vector[i]
		}
	}
	vinv, err := v.Inverse()
	if err != nil {
		return nil, ErrNotNormal
	}
	d := NewMatrix(n, n)
	for i := 0; i < n; i++ {
		d.data[i*n+i] = f(pairs[i].Value)
	}
	tmp, _ := v.Mul(d)
	return tmp.Mul(vinv)
}

// Exp returns the matrix exponential exp(m) computed with the scaling and
// squaring method combined with a truncated Taylor series. It is valid for any
// square matrix. It returns ErrNotSquare for a non-square matrix.
func (m *Matrix) Exp() (*Matrix, error) {
	if !m.IsSquare() {
		return nil, ErrNotSquare
	}
	n := m.rows
	if n == 0 {
		return NewMatrix(0, 0), nil
	}
	norm := m.InfNorm()
	s := 0
	for norm > 0.5 {
		norm /= 2
		s++
	}
	scale := complex(1/math.Pow(2, float64(s)), 0)
	b := m.Scale(scale)
	// Taylor series sum_{k>=0} b^k / k!.
	result := Identity(n)
	term := Identity(n)
	for k := 1; k <= 30; k++ {
		term, _ = term.Mul(b)
		term = term.Scale(complex(1/float64(k), 0))
		result, _ = result.Add(term)
		if term.MaxAbs() <= 1e-18 {
			break
		}
	}
	for i := 0; i < s; i++ {
		result, _ = result.Mul(result)
	}
	return result, nil
}

// Log returns a matrix logarithm of m via the functional calculus, so that
// exp(Log(m)) = m for a diagonalisable m with eigenvalues off the negative real
// axis. It returns an error for a non-square or defective matrix.
func (m *Matrix) Log() (*Matrix, error) {
	return m.ApplyFunction(cmplx.Log)
}

// Sqrt returns the principal square root of m via the functional calculus, so
// that Sqrt(m)^2 = m for a diagonalisable m. For a Hermitian positive
// semidefinite matrix this is the unique positive semidefinite square root.
func (m *Matrix) Sqrt() (*Matrix, error) {
	return m.ApplyFunction(cmplx.Sqrt)
}

// Sin returns the matrix sine sin(m) via the functional calculus.
func (m *Matrix) Sin() (*Matrix, error) {
	return m.ApplyFunction(cmplx.Sin)
}

// Cos returns the matrix cosine cos(m) via the functional calculus.
func (m *Matrix) Cos() (*Matrix, error) {
	return m.ApplyFunction(cmplx.Cos)
}

// Sign returns the matrix sign function, mapping each eigenvalue lambda to
// sign(Re lambda) (and 0 when Re lambda is 0). For a Hermitian matrix this is
// the difference of the projectors onto the positive and negative eigenspaces.
func (m *Matrix) Sign() (*Matrix, error) {
	return m.ApplyFunction(func(z complex128) complex128 {
		switch {
		case real(z) > 0:
			return 1
		case real(z) < 0:
			return -1
		default:
			return 0
		}
	})
}

// PowerReal returns m raised to a real power p via the functional calculus,
// exp(p*Log(m)). For a Hermitian positive definite matrix and integer p it
// agrees with the ordinary matrix power.
func (m *Matrix) PowerReal(p float64) (*Matrix, error) {
	return m.ApplyFunction(func(z complex128) complex128 {
		return cmplx.Pow(z, complex(p, 0))
	})
}

// Cosh returns the matrix hyperbolic cosine cosh(m) via the functional
// calculus.
func (m *Matrix) Cosh() (*Matrix, error) {
	return m.ApplyFunction(cmplx.Cosh)
}

// Sinh returns the matrix hyperbolic sine sinh(m) via the functional calculus.
func (m *Matrix) Sinh() (*Matrix, error) {
	return m.ApplyFunction(cmplx.Sinh)
}

// Semigroup returns exp(t*m), the value at time t of the one-parameter operator
// semigroup generated by m.
func (m *Matrix) Semigroup(t float64) (*Matrix, error) {
	return m.Scale(complex(t, 0)).Exp()
}

// Resolvent-based Cayley transform.

// CayleyTransform returns (m - i*I)(m + i*I)^{-1}, which maps a Hermitian
// operator to a unitary one. It returns ErrSingular if m + i*I is singular.
func (m *Matrix) CayleyTransform() (*Matrix, error) {
	if !m.IsSquare() {
		return nil, ErrNotSquare
	}
	n := m.rows
	num := m.Clone()
	den := m.Clone()
	for i := 0; i < n; i++ {
		num.data[i*n+i] -= complex(0, 1)
		den.data[i*n+i] += complex(0, 1)
	}
	dinv, err := den.Inverse()
	if err != nil {
		return nil, err
	}
	return num.Mul(dinv)
}
