package lattices

import "math/big"

// subRow performs dst -= q*src over the first n columns.
func subRow(dst, src []*big.Int, q *big.Int, n int) {
	if q.Sign() == 0 {
		return
	}
	t := new(big.Int)
	for k := 0; k < n; k++ {
		t.Mul(q, src[k])
		dst[k].Sub(dst[k], t)
	}
}

// negRow negates the first n entries of a row.
func negRow(row []*big.Int, n int) {
	for k := 0; k < n; k++ {
		row[k].Neg(row[k])
	}
}

// hnfCore reduces a (and applies the identical row operations to u, if non-nil)
// to row Hermite normal form in place and returns the number of pivot rows.
func hnfCore(a [][]*big.Int, u [][]*big.Int, rows, cols, ucols int) int {
	r := 0
	swap := func(i, j int) {
		a[i], a[j] = a[j], a[i]
		if u != nil {
			u[i], u[j] = u[j], u[i]
		}
	}
	sub := func(i, base int, q *big.Int) {
		subRow(a[i], a[base], q, cols)
		if u != nil {
			subRow(u[i], u[base], q, ucols)
		}
	}
	neg := func(i int) {
		negRow(a[i], cols)
		if u != nil {
			negRow(u[i], ucols)
		}
	}
	for j := 0; j < cols && r < rows; j++ {
		for {
			p := -1
			for i := r; i < rows; i++ {
				if a[i][j].Sign() != 0 && (p == -1 || a[i][j].CmpAbs(a[p][j]) < 0) {
					p = i
				}
			}
			if p == -1 {
				break
			}
			if p != r {
				swap(p, r)
			}
			reduced := false
			for i := r + 1; i < rows; i++ {
				if a[i][j].Sign() != 0 {
					q := new(big.Int).Quo(a[i][j], a[r][j])
					sub(i, r, q)
					reduced = true
				}
			}
			if !reduced {
				break
			}
		}
		if a[r][j].Sign() == 0 {
			continue
		}
		if a[r][j].Sign() < 0 {
			neg(r)
		}
		for i := 0; i < r; i++ {
			if a[i][j].Sign() != 0 {
				q := new(big.Int)
				m := new(big.Int)
				q.DivMod(a[i][j], a[r][j], m)
				sub(i, r, q)
			}
		}
		r++
	}
	return r
}

// HermiteNormalForm returns the row Hermite normal form of the integer matrix:
// an upper-triangular row-echelon matrix H obtained from m by unimodular row
// operations, with positive pivots and every entry above a pivot reduced into
// the half-open interval [0, pivot). The lattice generated by the rows of m is
// preserved.
func (m IntMatrix) HermiteNormalForm() IntMatrix {
	h := m.Clone()
	hnfCore(h.data, nil, h.rows, h.cols, 0)
	return h
}

// HermiteNormalFormWithTransform returns the Hermite normal form H together with
// a unimodular matrix U such that U*m = H.
func (m IntMatrix) HermiteNormalFormWithTransform() (h IntMatrix, u IntMatrix) {
	h = m.Clone()
	u = IdentityIntMatrix(m.rows)
	hnfCore(h.data, u.data, h.rows, h.cols, u.cols)
	return h, u
}

// HNFRank returns the number of nonzero pivot rows in the Hermite normal form,
// which equals the rank of the integer matrix.
func (m IntMatrix) HNFRank() int {
	h := m.Clone()
	return hnfCore(h.data, nil, h.rows, h.cols, 0)
}

// IsHermiteNormalForm reports whether m is already in row Hermite normal form:
// pivots occur in strictly increasing columns, every pivot is positive, entries
// below pivots are zero and entries above a pivot lie in [0, pivot).
func (m IntMatrix) IsHermiteNormalForm() bool {
	prevCol := -1
	pivotCols := make([]int, 0, m.rows)
	pivotRows := make([]int, 0, m.rows)
	for i := 0; i < m.rows; i++ {
		j := 0
		for j < m.cols && m.data[i][j].Sign() == 0 {
			j++
		}
		if j == m.cols {
			// zero row: all subsequent rows must also be zero
			for k := i + 1; k < m.rows; k++ {
				for c := 0; c < m.cols; c++ {
					if m.data[k][c].Sign() != 0 {
						return false
					}
				}
			}
			break
		}
		if j <= prevCol {
			return false
		}
		if m.data[i][j].Sign() <= 0 {
			return false
		}
		// below-pivot entries must be zero
		for k := i + 1; k < m.rows; k++ {
			if m.data[k][j].Sign() != 0 {
				return false
			}
		}
		prevCol = j
		pivotCols = append(pivotCols, j)
		pivotRows = append(pivotRows, i)
	}
	// above-pivot reduction check
	for idx, j := range pivotCols {
		pr := pivotRows[idx]
		piv := m.data[pr][j]
		for k := 0; k < pr; k++ {
			e := m.data[k][j]
			if e.Sign() < 0 || e.Cmp(piv) >= 0 {
				return false
			}
		}
	}
	return true
}

// HermiteNormalForm returns the row Hermite normal form of an integer basis. It
// returns ErrBadParameter if the basis has non-integer entries and ErrEmpty for
// an empty basis.
func (b Basis) HermiteNormalForm() (IntMatrix, error) {
	if len(b) == 0 {
		return IntMatrix{}, ErrEmpty
	}
	im, err := IntMatrixFromBasis(b)
	if err != nil {
		return IntMatrix{}, err
	}
	return im.HermiteNormalForm(), nil
}

// SameLattice reports whether two integer bases of the same ambient dimension
// generate the same lattice, by comparing their Hermite normal forms. It
// returns ErrBadParameter if either basis has non-integer entries.
func SameLattice(a, b Basis) (bool, error) {
	if a.Dim() != b.Dim() {
		return false, nil
	}
	ha, err := a.HermiteNormalForm()
	if err != nil {
		return false, err
	}
	hb, err := b.HermiteNormalForm()
	if err != nil {
		return false, err
	}
	// Drop trailing zero rows before comparison.
	return trimZeroRows(ha).Equal(trimZeroRows(hb)), nil
}

// trimZeroRows returns m without its trailing all-zero rows.
func trimZeroRows(m IntMatrix) IntMatrix {
	last := m.rows
	for last > 0 {
		allZero := true
		for j := 0; j < m.cols; j++ {
			if m.data[last-1][j].Sign() != 0 {
				allZero = false
				break
			}
		}
		if !allZero {
			break
		}
		last--
	}
	if last == m.rows {
		return m
	}
	out := ZeroIntMatrix(last, m.cols)
	for i := 0; i < last; i++ {
		for j := 0; j < m.cols; j++ {
			out.data[i][j].Set(m.data[i][j])
		}
	}
	return out
}
