package quasirandom

import "math"

// GoldenRatio is the golden ratio phi = (1+sqrt5)/2, the optimal irrational for
// a one-dimensional Kronecker (Weyl) sequence.
const GoldenRatio = 1.618033988749894848204586834365638117720309179805762862135

// GoldenRatioConjugate is 1/phi = phi-1 = 0.6180339887..., the increment of the
// canonical golden-ratio Weyl sequence.
const GoldenRatioConjugate = 0.6180339887498948482045868343656381177203091798057628621354

// Frac returns the fractional part of x in the half-open interval [0,1),
// computed as x - floor(x) so that negative inputs also map into [0,1).
func Frac(x float64) float64 {
	f := x - math.Floor(x)
	if f >= 1 {
		f = 0
	}
	return f
}

// ClampUnit clamps x into the closed unit interval [0,1].
func ClampUnit(x float64) float64 {
	if x < 0 {
		return 0
	}
	if x > 1 {
		return 1
	}
	return x
}

// WeylSequence returns the n-th term (zero-based) of the one-dimensional Weyl
// (Kronecker) sequence with irrational parameter alpha, namely the fractional
// part of n*alpha.
func WeylSequence(alpha float64, n uint64) float64 {
	return Frac(float64(n) * alpha)
}

// GoldenRatioSequence returns count terms of the Weyl sequence generated by the
// golden ratio, the best-distributed one-dimensional additive sequence.
func GoldenRatioSequence(count int) ([]float64, error) {
	if count < 0 {
		return nil, ErrNonPositive
	}
	out := make([]float64, count)
	for i := 0; i < count; i++ {
		out[i] = Frac(float64(i) * GoldenRatio)
	}
	return out, nil
}

// KroneckerPoint returns the n-th point (zero-based) of the multi-dimensional
// Kronecker sequence with generating vector alpha, the fractional part of
// n*alpha in each coordinate. It returns an error when alpha is empty.
func KroneckerPoint(alpha []float64, n uint64) ([]float64, error) {
	if len(alpha) == 0 {
		return nil, ErrDimension
	}
	out := make([]float64, len(alpha))
	for k, a := range alpha {
		out[k] = Frac(float64(n) * a)
	}
	return out, nil
}

// KroneckerSequence returns the first count points of the Kronecker sequence
// with generating vector alpha.
func KroneckerSequence(alpha []float64, count int) ([][]float64, error) {
	if len(alpha) == 0 {
		return nil, ErrDimension
	}
	if count < 0 {
		return nil, ErrNonPositive
	}
	out := make([][]float64, count)
	for i := 0; i < count; i++ {
		p, err := KroneckerPoint(alpha, uint64(i))
		if err != nil {
			return nil, err
		}
		out[i] = p
	}
	return out, nil
}

// PlasticConstant returns the generalized golden ratio for the given dimension:
// the unique real root greater than one of x^(dim+1) = x + 1. For dim==1 this is
// the golden ratio and for dim==2 the plastic number 1.3247... It returns an
// error when dim < 1.
func PlasticConstant(dim int) (float64, error) {
	if dim < 1 {
		return 0, ErrDimension
	}
	// Solve x^(dim+1) - x - 1 = 0 by Newton's method from x0 = 1.
	x := 1.5
	for iter := 0; iter < 200; iter++ {
		xp := math.Pow(x, float64(dim)) // x^dim
		f := xp*x - x - 1               // x^(dim+1) - x - 1
		df := float64(dim+1)*xp - 1     // (dim+1)x^dim - 1
		if df == 0 {
			break
		}
		dx := f / df
		x -= dx
		if math.Abs(dx) < 1e-15 {
			break
		}
	}
	return x, nil
}

// RobertsAlpha returns the generating vector of Roberts' R_d low-discrepancy
// additive sequence in the given dimension: alpha_j = frac(g^-j) where g is the
// plastic constant PlasticConstant(dim). It returns an error when dim < 1.
func RobertsAlpha(dim int) ([]float64, error) {
	g, err := PlasticConstant(dim)
	if err != nil {
		return nil, err
	}
	inv := 1 / g
	out := make([]float64, dim)
	p := 1.0
	for j := 0; j < dim; j++ {
		p *= inv
		out[j] = Frac(p)
	}
	return out, nil
}

// RobertsPoint returns the n-th point (zero-based) of Roberts' R_d additive
// low-discrepancy sequence in the given dimension, using the seed 1/2 so that
// point zero sits at the center of the cube. It returns an error when dim < 1.
func RobertsPoint(dim int, n uint64) ([]float64, error) {
	alpha, err := RobertsAlpha(dim)
	if err != nil {
		return nil, err
	}
	out := make([]float64, dim)
	for k, a := range alpha {
		out[k] = Frac(0.5 + float64(n)*a)
	}
	return out, nil
}

// RobertsSequence returns the first count points of Roberts' R_d sequence in the
// given dimension.
func RobertsSequence(dim, count int) ([][]float64, error) {
	if count < 0 {
		return nil, ErrNonPositive
	}
	alpha, err := RobertsAlpha(dim)
	if err != nil {
		return nil, err
	}
	out := make([][]float64, count)
	for i := 0; i < count; i++ {
		p := make([]float64, dim)
		for k, a := range alpha {
			p[k] = Frac(0.5 + float64(i)*a)
		}
		out[i] = p
	}
	return out, nil
}

// AdditiveRecurrenceSequence returns count terms of the one-dimensional additive
// recurrence x_{n} = frac(seed + n*alpha), a shifted Weyl sequence.
func AdditiveRecurrenceSequence(seed, alpha float64, count int) ([]float64, error) {
	if count < 0 {
		return nil, ErrNonPositive
	}
	out := make([]float64, count)
	for i := 0; i < count; i++ {
		out[i] = Frac(seed + float64(i)*alpha)
	}
	return out, nil
}
