package quasirandom

// sobolBits is the number of bits of resolution used for Sobol direction
// numbers. With 52 bits every scaled direction integer is below 2^52 and the
// division by 2^52 is exact in float64.
const sobolBits = 52

// sobolInit holds, for one dimension, the degree s of its primitive polynomial,
// the integer encoding a of the polynomial's interior coefficients, and the
// initial direction integers m_1..m_s.
type sobolInit struct {
	s int
	a int
	m []int
}

// sobolTable lists the primitive-polynomial data for dimensions 2..21 in the
// classic Bratley–Fox / Joe–Kuo ordering. Dimension one is handled specially
// (all direction numbers equal to one) and is not stored here.
var sobolTable = []sobolInit{
	{1, 0, []int{1}},                 // dim 2
	{2, 1, []int{1, 3}},              // dim 3
	{3, 1, []int{1, 3, 1}},           // dim 4
	{3, 2, []int{1, 1, 1}},           // dim 5
	{4, 1, []int{1, 1, 3, 3}},        // dim 6
	{4, 4, []int{1, 3, 5, 13}},       // dim 7
	{5, 2, []int{1, 1, 5, 5, 17}},    // dim 8
	{5, 4, []int{1, 1, 5, 5, 5}},     // dim 9
	{5, 7, []int{1, 1, 7, 11, 19}},   // dim 10
	{5, 11, []int{1, 1, 5, 1, 1}},    // dim 11
	{5, 13, []int{1, 1, 1, 3, 11}},   // dim 12
	{5, 14, []int{1, 3, 5, 5, 31}},   // dim 13
	{6, 1, []int{1, 3, 3, 9, 7, 49}}, // dim 14
	{6, 13, []int{1, 1, 1, 15, 21, 21}},
	{6, 16, []int{1, 3, 1, 13, 27, 49}},
	{6, 19, []int{1, 1, 1, 15, 7, 5}},
	{6, 22, []int{1, 3, 1, 15, 13, 25}},
	{6, 25, []int{1, 1, 5, 5, 19, 61}},
	{7, 1, []int{1, 3, 7, 11, 23, 39, 5}}, // dim 20
	{7, 4, []int{1, 3, 7, 13, 25, 5, 49}}, // dim 21
}

// MaxSobolDimension returns the largest dimension for which built-in direction
// numbers are available (dimensions 1 through this value inclusive).
func MaxSobolDimension() int { return len(sobolTable) + 1 }

// PrimitivePolynomialDegree returns the degree of the primitive polynomial used
// for the given Sobol dimension. Dimension one uses the trivial degree-zero
// polynomial. It returns an error when dim is out of range.
func PrimitivePolynomialDegree(dim int) (int, error) {
	if dim < 1 || dim > MaxSobolDimension() {
		return 0, ErrDimension
	}
	if dim == 1 {
		return 0, nil
	}
	return sobolTable[dim-2].s, nil
}

// PrimitivePolynomialEncoding returns the integer that encodes the interior
// coefficients a_1..a_{s-1} of the primitive polynomial for the given Sobol
// dimension, with a_1 the most significant bit. It returns an error when dim is
// out of range.
func PrimitivePolynomialEncoding(dim int) (int, error) {
	if dim < 1 || dim > MaxSobolDimension() {
		return 0, ErrDimension
	}
	if dim == 1 {
		return 0, nil
	}
	return sobolTable[dim-2].a, nil
}

// PrimitivePolynomialCoefficients returns the full coefficient vector of the
// primitive polynomial for the given Sobol dimension, ordered from the leading
// x^s term down to the constant term. Both the leading and constant
// coefficients are one. It returns an error when dim is out of range.
func PrimitivePolynomialCoefficients(dim int) ([]int, error) {
	s, err := PrimitivePolynomialDegree(dim)
	if err != nil {
		return nil, err
	}
	if s == 0 {
		return []int{1}, nil
	}
	a, _ := PrimitivePolynomialEncoding(dim)
	coeffs := make([]int, s+1)
	coeffs[0] = 1
	coeffs[s] = 1
	for k := 1; k <= s-1; k++ {
		coeffs[k] = (a >> (s - 1 - k)) & 1
	}
	return coeffs, nil
}

// InitialDirectionNumbers returns the initial direction integers m_1..m_s for
// the given Sobol dimension. Dimension one returns the single value one.
// It returns an error when dim is out of range.
func InitialDirectionNumbers(dim int) ([]int, error) {
	if dim < 1 || dim > MaxSobolDimension() {
		return nil, ErrDimension
	}
	if dim == 1 {
		return []int{1}, nil
	}
	return append([]int(nil), sobolTable[dim-2].m...), nil
}

// directionIntegers builds the full vector of scaled direction integers
// V_1..V_bits for one Sobol dimension. V_i equals m_i shifted left by bits-i so
// that V_i / 2^bits equals the fractional direction number m_i / 2^i.
func directionIntegers(dim, bits int) ([]uint64, error) {
	if dim < 1 || dim > MaxSobolDimension() {
		return nil, ErrDimension
	}
	v := make([]uint64, bits+1) // index 1..bits
	if dim == 1 {
		for i := 1; i <= bits; i++ {
			v[i] = uint64(1) << uint(bits-i)
		}
		return v, nil
	}
	info := sobolTable[dim-2]
	s := info.s
	a := info.a
	for i := 1; i <= s && i <= bits; i++ {
		v[i] = uint64(info.m[i-1]) << uint(bits-i)
	}
	for i := s + 1; i <= bits; i++ {
		val := v[i-s] ^ (v[i-s] >> uint(s))
		for k := 1; k <= s-1; k++ {
			if (a>>(s-1-k))&1 == 1 {
				val ^= v[i-k]
			}
		}
		v[i] = val
	}
	return v, nil
}

// DirectionNumbers returns the fractional direction numbers m_i / 2^i for the
// given Sobol dimension, one value per bit of resolution, as computed from the
// recurrence generated by the dimension's primitive polynomial. It returns an
// error when dim is out of range.
func DirectionNumbers(dim int) ([]float64, error) {
	v, err := directionIntegers(dim, sobolBits)
	if err != nil {
		return nil, err
	}
	scale := 1.0 / float64(uint64(1)<<sobolBits)
	out := make([]float64, sobolBits)
	for i := 1; i <= sobolBits; i++ {
		out[i-1] = float64(v[i]) * scale
	}
	return out, nil
}

// Sobol is a stateful generator of the multi-dimensional Sobol sequence. It
// yields successive points in Gray-code order via the Antonov–Saleev recurrence
// and may also address any point directly. The zero value is not usable; obtain
// one from NewSobol.
type Sobol struct {
	dim   int
	bits  int
	v     [][]uint64 // v[d] indexed 1..bits
	state []uint64
	count uint64
	scale float64
}

// NewSobol returns a Sobol generator for the given dimension using the built-in
// direction numbers. The first point produced by Next is the origin. It returns
// an error when dim is out of the supported range.
func NewSobol(dim int) (*Sobol, error) {
	if dim < 1 || dim > MaxSobolDimension() {
		return nil, ErrDimension
	}
	s := &Sobol{
		dim:   dim,
		bits:  sobolBits,
		v:     make([][]uint64, dim),
		state: make([]uint64, dim),
		scale: 1.0 / float64(uint64(1)<<sobolBits),
	}
	for d := 0; d < dim; d++ {
		vd, err := directionIntegers(d+1, sobolBits)
		if err != nil {
			return nil, err
		}
		s.v[d] = vd
	}
	return s, nil
}

// Dimension returns the number of coordinates the generator produces.
func (s *Sobol) Dimension() int { return s.dim }

// Index returns the zero-based index of the point that the next call to Next
// will return.
func (s *Sobol) Index() uint64 { return s.count }

// Reset returns the generator to its initial state, so the next call to Next
// again yields the origin.
func (s *Sobol) Reset() {
	for d := range s.state {
		s.state[d] = 0
	}
	s.count = 0
}

// Next returns the current Sobol point and advances the generator by one index
// using the Antonov–Saleev Gray-code recurrence. The returned slice is freshly
// allocated and owned by the caller.
func (s *Sobol) Next() []float64 {
	out := make([]float64, s.dim)
	for d := 0; d < s.dim; d++ {
		out[d] = float64(s.state[d]) * s.scale
	}
	c := LowestZeroBit(s.count)
	if c < s.bits {
		for d := 0; d < s.dim; d++ {
			s.state[d] ^= s.v[d][c+1]
		}
	}
	s.count++
	return out
}

// Point returns the n-th Sobol point (zero-based) directly, without disturbing
// the generator's streaming state, by expanding the Gray code of n.
func (s *Sobol) Point(n uint64) []float64 {
	g := GrayCode(n)
	out := make([]float64, s.dim)
	acc := make([]uint64, s.dim)
	for i := 0; g != 0; i++ {
		if g&1 == 1 {
			for d := 0; d < s.dim; d++ {
				acc[d] ^= s.v[d][i+1]
			}
		}
		g >>= 1
	}
	for d := 0; d < s.dim; d++ {
		out[d] = float64(acc[d]) * s.scale
	}
	return out
}

// Skip advances the generator by k indices without returning the intervening
// points, leaving it positioned so that the next Next returns point Index()+k.
func (s *Sobol) Skip(k uint64) {
	for i := uint64(0); i < k; i++ {
		c := LowestZeroBit(s.count)
		if c < s.bits {
			for d := 0; d < s.dim; d++ {
				s.state[d] ^= s.v[d][c+1]
			}
		}
		s.count++
	}
}

// SobolPoint returns the n-th point (zero-based) of the dim-dimensional Sobol
// sequence directly. It builds the direction numbers on each call; for
// streaming use a Sobol generator instead. It returns an error when dim is out
// of range.
func SobolPoint(dim int, n uint64) ([]float64, error) {
	if dim < 1 || dim > MaxSobolDimension() {
		return nil, ErrDimension
	}
	s, err := NewSobol(dim)
	if err != nil {
		return nil, err
	}
	return s.Point(n), nil
}

// SobolSequence returns the first count points of the dim-dimensional Sobol
// sequence beginning at the origin (index zero).
func SobolSequence(dim, count int) ([][]float64, error) {
	if count < 0 {
		return nil, ErrNonPositive
	}
	s, err := NewSobol(dim)
	if err != nil {
		return nil, err
	}
	out := make([][]float64, count)
	for i := 0; i < count; i++ {
		out[i] = s.Next()
	}
	return out, nil
}

// SobolSequenceSkip returns count Sobol points after first skipping the leading
// skip points (a common way to discard the origin and low-index samples).
func SobolSequenceSkip(dim, skip, count int) ([][]float64, error) {
	if count < 0 || skip < 0 {
		return nil, ErrNonPositive
	}
	s, err := NewSobol(dim)
	if err != nil {
		return nil, err
	}
	s.Skip(uint64(skip))
	out := make([][]float64, count)
	for i := 0; i < count; i++ {
		out[i] = s.Next()
	}
	return out, nil
}
