package tilings

import (
	"math"
	"sort"
)

// FriezeGroup describes one of the 7 frieze groups, the discrete symmetry
// groups of an infinitely long strip with translations along a single axis
// (taken to be the x-axis with period Period). The group is generated by its
// coset representatives together with the axial translations.
type FriezeGroup struct {
	// IUC is the Hermann-Mauguin symbol, e.g. "p2mg".
	IUC string
	// Orbifold is Conway's orbifold symbol, e.g. "22*".
	Orbifold string
	// Nickname is Conway's descriptive name, e.g. "spinning sidle".
	Nickname string
	// Period is the translation period along the x-axis.
	Period float64
	// generators build the coset representatives.
	generators []Isometry
	// cosets are the representatives modulo axial translation.
	cosets []Isometry
}

// friezeSpec is the static definition of a frieze group.
type friezeSpec struct {
	iuc, orbifold, nick string
	makeGens            func(period float64) []Isometry
}

var friezeSpecs = []friezeSpec{
	{"p1", "∞∞", "hop", func(p float64) []Isometry { return nil }},
	{"p11g", "∞x", "step", func(p float64) []Isometry {
		return []Isometry{withTrans(linMy, Point{p / 2, 0})}
	}},
	{"p1m1", "*∞∞", "sidle", func(p float64) []Isometry { return []Isometry{linMx} }},
	{"p2", "22∞", "spinning hop", func(p float64) []Isometry { return []Isometry{linR2} }},
	{"p2mg", "2*∞", "spinning sidle", func(p float64) []Isometry {
		return []Isometry{linR2, withTrans(linMy, Point{p / 2, 0})}
	}},
	{"p11m", "∞*", "jump", func(p float64) []Isometry { return []Isometry{linMy} }},
	{"p2mm", "*22∞", "spinning jump", func(p float64) []Isometry { return []Isometry{linMx, linMy} }},
}

// closeFriezeCosets closes the generators modulo axial translation of the given
// period.
func closeFriezeCosets(gens []Isometry, period float64) []Isometry {
	reduce := func(a Isometry) Isometry {
		x := a.Tx
		x -= period * math.Floor(x/period+1e-12)
		a.Tx = x
		return a
	}
	start := reduce(Identity())
	reps := []Isometry{start}
	seen := map[string]bool{isoKey(start): true}
	var moves []Isometry
	for _, g := range gens {
		moves = append(moves, g, g.Inverse())
	}
	queue := []Isometry{start}
	for len(queue) > 0 && len(reps) < 1024 {
		cur := queue[0]
		queue = queue[1:]
		for _, m := range moves {
			n := reduce(m.Compose(cur))
			k := isoKey(n)
			if !seen[k] {
				seen[k] = true
				reps = append(reps, n)
				queue = append(queue, n)
			}
		}
	}
	return reps
}

// buildFrieze realises a frieze group with the given period.
func buildFrieze(s friezeSpec, period float64) FriezeGroup {
	gens := s.makeGens(period)
	return FriezeGroup{
		IUC:        s.iuc,
		Orbifold:   s.orbifold,
		Nickname:   s.nick,
		Period:     period,
		generators: gens,
		cosets:     closeFriezeCosets(gens, period),
	}
}

// FriezeGroups returns all 7 frieze groups with unit period in the conventional
// order (p1, p11g, p1m1, p2, p2mg, p11m, p2mm).
func FriezeGroups() []FriezeGroup {
	out := make([]FriezeGroup, len(friezeSpecs))
	for i, s := range friezeSpecs {
		out[i] = buildFrieze(s, 1)
	}
	return out
}

// FriezeGroupByIUC returns the frieze group with the given Hermann-Mauguin
// symbol at unit period and reports whether it was found.
func FriezeGroupByIUC(iuc string) (FriezeGroup, bool) {
	for _, s := range friezeSpecs {
		if s.iuc == iuc {
			return buildFrieze(s, 1), true
		}
	}
	return FriezeGroup{}, false
}

// FriezeIUCNames returns the 7 Hermann-Mauguin symbols in conventional order.
func FriezeIUCNames() []string {
	out := make([]string, len(friezeSpecs))
	for i, s := range friezeSpecs {
		out[i] = s.iuc
	}
	return out
}

// Cosets returns the coset representatives of the frieze group modulo axial
// translation.
func (g FriezeGroup) Cosets() []Isometry {
	out := make([]Isometry, len(g.cosets))
	copy(out, g.cosets)
	return out
}

// PointGroupOrder returns the order of the associated point group, equal to the
// number of coset representatives.
func (g FriezeGroup) PointGroupOrder() int { return len(g.cosets) }

// HasReflection reports whether the group contains a reflection.
func (g FriezeGroup) HasReflection() bool {
	for _, c := range g.cosets {
		if c.Classify(1e-9).Kind == KindReflection {
			return true
		}
	}
	return false
}

// HasGlideReflection reports whether the group contains a glide reflection.
func (g FriezeGroup) HasGlideReflection() bool {
	for _, c := range g.cosets {
		if c.Classify(1e-9).Kind == KindGlideReflection {
			return true
		}
	}
	return false
}

// HasRotation reports whether the group contains a 180-degree rotation.
func (g FriezeGroup) HasRotation() bool {
	for _, c := range g.cosets {
		if c.Classify(1e-9).Kind == KindRotation {
			return true
		}
	}
	return false
}

// GroupElements returns the isometries of the group whose translation lies
// within n periods of the origin.
func (g FriezeGroup) GroupElements(n int) []Isometry {
	if n < 0 {
		return nil
	}
	var out []Isometry
	for i := -n; i <= n; i++ {
		t := Translation(float64(i)*g.Period, 0)
		for _, c := range g.cosets {
			out = append(out, t.Compose(c))
		}
	}
	return out
}

// Orbit returns the images of the point p under GroupElements(n), deduplicated
// to within eps and sorted for determinism.
func (g FriezeGroup) Orbit(p Point, n int, eps float64) []Point {
	var out []Point
	for _, e := range g.GroupElements(n) {
		q := e.Apply(p)
		dup := false
		for _, r := range out {
			if r.ApproxEqual(q, eps) {
				dup = true
				break
			}
		}
		if !dup {
			out = append(out, q)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if math.Abs(out[i].X-out[j].X) > eps {
			return out[i].X < out[j].X
		}
		return out[i].Y < out[j].Y
	})
	return out
}
