package tilings

import (
	"math"
	"sort"
)

// Lattice2D is a two-dimensional lattice generated by integer combinations of
// two basis vectors V1 and V2. The basis must be non-degenerate (V1 and V2
// linearly independent).
type Lattice2D struct {
	V1, V2 Point
}

// NewLattice2D returns the lattice with the given basis vectors.
func NewLattice2D(v1, v2 Point) Lattice2D { return Lattice2D{V1: v1, V2: v2} }

// SquareLattice returns the square lattice of spacing a.
func SquareLattice(a float64) Lattice2D {
	return Lattice2D{V1: Point{a, 0}, V2: Point{0, a}}
}

// RectangularLattice returns the rectangular lattice with spacings a and b.
func RectangularLattice(a, b float64) Lattice2D {
	return Lattice2D{V1: Point{a, 0}, V2: Point{0, b}}
}

// HexagonalLattice returns the hexagonal (triangular) lattice of spacing a,
// with basis vectors at 0 and 60 degrees.
func HexagonalLattice(a float64) Lattice2D {
	return Lattice2D{V1: Point{a, 0}, V2: Point{a / 2, a * math.Sqrt(3) / 2}}
}

// RhombicLattice returns the centred-rectangular (rhombic) lattice with
// primitive basis (a/2, h) and (-a/2, h).
func RhombicLattice(a, h float64) Lattice2D {
	return Lattice2D{V1: Point{a / 2, h}, V2: Point{-a / 2, h}}
}

// ObliqueLattice returns a generic oblique lattice with the given basis lengths
// and included angle gamma (radians).
func ObliqueLattice(a, b, gamma float64) Lattice2D {
	return Lattice2D{V1: Point{a, 0}, V2: Point{b * math.Cos(gamma), b * math.Sin(gamma)}}
}

// FundamentalArea returns the area of the lattice's fundamental parallelogram,
// the absolute value of the cross product of the basis vectors.
func (l Lattice2D) FundamentalArea() float64 {
	return math.Abs(l.V1.Cross(l.V2))
}

// Point returns the lattice point i*V1 + j*V2.
func (l Lattice2D) Point(i, j int) Point {
	return l.V1.Scale(float64(i)).Add(l.V2.Scale(float64(j)))
}

// ToFractional returns the coordinates (a, b) of p in the basis, so that
// p = a*V1 + b*V2.
func (l Lattice2D) ToFractional(p Point) (float64, float64) {
	det := l.V1.Cross(l.V2)
	a := (p.X*l.V2.Y - p.Y*l.V2.X) / det
	b := (l.V1.X*p.Y - l.V1.Y*p.X) / det
	return a, b
}

// FromFractional returns the point a*V1 + b*V2.
func (l Lattice2D) FromFractional(a, b float64) Point {
	return l.V1.Scale(a).Add(l.V2.Scale(b))
}

// Reduce returns the representative of p modulo the lattice lying in the
// fundamental parallelogram [0,1) x [0,1) in basis coordinates.
func (l Lattice2D) Reduce(p Point) Point {
	a, b := l.ToFractional(p)
	a -= math.Floor(a + 1e-12)
	b -= math.Floor(b + 1e-12)
	return l.FromFractional(a, b)
}

// NearestPoint returns the lattice point closest to p (by rounding basis
// coordinates); it is exact for well-conditioned bases.
func (l Lattice2D) NearestPoint(p Point) Point {
	a, b := l.ToFractional(p)
	return l.Point(int(math.Round(a)), int(math.Round(b)))
}

// Gram returns the Gram matrix entries (g11, g12, g22) of the basis, namely
// V1·V1, V1·V2 and V2·V2.
func (l Lattice2D) Gram() (g11, g12, g22 float64) {
	return l.V1.Dot(l.V1), l.V1.Dot(l.V2), l.V2.Dot(l.V2)
}

// Dual returns the dual (reciprocal) lattice, whose basis vectors W satisfy
// Wi·Vj = delta_ij.
func (l Lattice2D) Dual() Lattice2D {
	det := l.V1.Cross(l.V2)
	// Rows of (B^-1)^T where B has rows V1, V2.
	w1 := Point{l.V2.Y / det, -l.V2.X / det}
	w2 := Point{-l.V1.Y / det, l.V1.X / det}
	return Lattice2D{V1: w1, V2: w2}
}

// GaussReduced returns a Gauss/Lagrange-reduced basis for the same lattice: two
// shortest vectors realising the successive minima, with V1 no longer than V2.
func (l Lattice2D) GaussReduced() Lattice2D {
	v1, v2 := l.V1, l.V2
	if v1.Norm2() > v2.Norm2() {
		v1, v2 = v2, v1
	}
	for {
		m := math.Round(v1.Dot(v2) / v1.Norm2())
		v2 = v2.Sub(v1.Scale(m))
		if v2.Norm2() >= v1.Norm2() {
			break
		}
		v1, v2 = v2, v1
	}
	return Lattice2D{V1: v1, V2: v2}
}

// ShortestVector returns a nonzero lattice vector of minimum length.
func (l Lattice2D) ShortestVector() Point { return l.GaussReduced().V1 }

// ShortestLength returns the length of a shortest nonzero lattice vector, the
// square root of the minimum squared distance.
func (l Lattice2D) ShortestLength() float64 { return l.ShortestVector().Norm() }

// PackingRadius returns the packing radius of the lattice, half the length of a
// shortest nonzero vector.
func (l Lattice2D) PackingRadius() float64 { return l.ShortestLength() / 2 }

// LatticeType enumerates the five Bravais lattice classes in the plane.
type LatticeType int

const (
	// Oblique is the generic lattice with no special symmetry.
	Oblique LatticeType = iota
	// Rectangular is a lattice with a rectangular primitive cell.
	Rectangular
	// CenteredRectangular is the centred-rectangular (rhombic) lattice.
	CenteredRectangular
	// Square is a lattice with four-fold symmetry.
	Square
	// Hexagonal is a lattice with six-fold symmetry.
	Hexagonal
)

// String returns the name of the lattice type.
func (t LatticeType) String() string {
	switch t {
	case Oblique:
		return "oblique"
	case Rectangular:
		return "rectangular"
	case CenteredRectangular:
		return "centered rectangular"
	case Square:
		return "square"
	case Hexagonal:
		return "hexagonal"
	default:
		return "unknown"
	}
}

// Classify returns the Bravais lattice type of the lattice using tolerance eps,
// judged from a reduced basis.
func (l Lattice2D) Classify(eps float64) LatticeType {
	r := l.GaussReduced()
	a := r.V1.Norm()
	b := r.V2.Norm()
	dot := r.V1.Dot(r.V2)
	ang := AngleBetween(r.V1, r.V2)
	equal := math.Abs(a-b) <= eps*math.Max(a, b)
	right := math.Abs(dot) <= eps*a*b
	// Hexagonal: equal lengths at 60 or 120 degrees.
	if equal && (approxEqualScalar(ang, math.Pi/3, 1e-6) || approxEqualScalar(ang, 2*math.Pi/3, 1e-6)) {
		return Hexagonal
	}
	if equal && right {
		return Square
	}
	if right {
		return Rectangular
	}
	// Centred rectangular: equal lengths (rhombus) but not at 90/60/120.
	if equal {
		return CenteredRectangular
	}
	// A reduced basis whose shorter diagonal equals a basis length also signals
	// a centred-rectangular cell.
	sum := r.V1.Add(r.V2)
	diff := r.V1.Sub(r.V2)
	if approxEqualScalar(sum.Norm(), a, eps) || approxEqualScalar(diff.Norm(), a, eps) ||
		approxEqualScalar(sum.Norm(), b, eps) || approxEqualScalar(diff.Norm(), b, eps) {
		return CenteredRectangular
	}
	return Oblique
}

// PointGroupOrder returns the order of the holohedry (full point-symmetry
// group) of the lattice type: 2, 4, 4, 8 or 12 for oblique, rectangular,
// centred-rectangular, square and hexagonal respectively.
func (t LatticeType) PointGroupOrder() int {
	switch t {
	case Oblique:
		return 2
	case Rectangular, CenteredRectangular:
		return 4
	case Square:
		return 8
	case Hexagonal:
		return 12
	default:
		return 0
	}
}

// LatticePoints returns all lattice points i*V1 + j*V2 with i, j in
// [-n, n], in row-major order.
func (l Lattice2D) LatticePoints(n int) []Point {
	if n < 0 {
		return nil
	}
	out := make([]Point, 0, (2*n+1)*(2*n+1))
	for i := -n; i <= n; i++ {
		for j := -n; j <= n; j++ {
			out = append(out, l.Point(i, j))
		}
	}
	return out
}

// VoronoiRelevantVectors returns the lattice vectors whose bisecting lines bound
// the Voronoi cell of the origin (the Wigner-Seitz cell). For a planar lattice
// there are four or six such vectors up to sign; the returned slice lists all of
// them (both signs), sorted by length.
func (l Lattice2D) VoronoiRelevantVectors() []Point {
	r := l.GaussReduced()
	cands := []Point{r.V1, r.V2, r.V1.Add(r.V2), r.V1.Sub(r.V2)}
	var out []Point
	for _, v := range cands {
		out = append(out, v, v.Neg())
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Norm2() < out[j].Norm2() })
	return out
}
