package tilings

import (
	"fmt"
	"math"
	"sort"
)

// WallpaperGroup describes one of the 17 two-dimensional crystallographic
// (wallpaper) groups: its names, translation lattice and a finite set of coset
// representatives of the quotient by the translation subgroup. The full group
// is generated by the coset representatives together with all lattice
// translations.
type WallpaperGroup struct {
	// IUC is the short international (Hermann-Mauguin) symbol, e.g. "p4m".
	IUC string
	// Orbifold is Conway's orbifold symbol, e.g. "*442".
	Orbifold string
	// Lattice is the underlying Bravais lattice type.
	Lattice LatticeType
	// PointGroupName names the associated point group, e.g. "D4".
	PointGroupName string
	// lattice is the concrete translation lattice used for generation.
	lattice Lattice2D
	// generators are the isometries whose closure (with the lattice) yields the
	// coset representatives.
	generators []Isometry
	// cosets are the coset representatives of G modulo the translation lattice.
	cosets []Isometry
}

// buildLinear constructs an origin-fixing linear isometry from matrix entries.
func linIso(m00, m01, m10, m11 float64) Isometry {
	return Isometry{M00: m00, M01: m01, M10: m10, M11: m11}
}

var (
	linI  = linIso(1, 0, 0, 1)   // identity
	linR2 = linIso(-1, 0, 0, -1) // 180 rotation
	linMx = linIso(-1, 0, 0, 1)  // mirror across y-axis (x -> -x)
	linMy = linIso(1, 0, 0, -1)  // mirror across x-axis (y -> -y)
)

func withTrans(a Isometry, t Point) Isometry {
	a.Tx, a.Ty = t.X, t.Y
	return a
}

// isoKey builds a canonical string key for coset deduplication.
func isoKey(a Isometry) string {
	round := func(x float64) float64 {
		r := math.Round(x*1e6) / 1e6
		if r == 0 {
			return 0 // normalise negative zero
		}
		return r
	}
	return fmt.Sprintf("%g|%g|%g|%g|%g|%g",
		round(a.M00), round(a.M01), round(a.M10), round(a.M11),
		round(a.Tx), round(a.Ty))
}

// closeCosets builds the finite set of coset representatives of the group
// generated by gens together with the lattice translations, by breadth-first
// closure with translation parts reduced modulo the lattice.
func closeCosets(gens []Isometry, lat Lattice2D) []Isometry {
	reduce := func(a Isometry) Isometry {
		t := lat.Reduce(Point{a.Tx, a.Ty})
		a.Tx, a.Ty = t.X, t.Y
		return a
	}
	start := reduce(Identity())
	reps := []Isometry{start}
	seen := map[string]bool{isoKey(start): true}
	// Include generators and their inverses.
	var moves []Isometry
	for _, g := range gens {
		moves = append(moves, g, g.Inverse())
	}
	queue := []Isometry{start}
	for len(queue) > 0 && len(reps) < 4096 {
		cur := queue[0]
		queue = queue[1:]
		for _, m := range moves {
			n := reduce(m.Compose(cur))
			k := isoKey(n)
			if !seen[k] {
				seen[k] = true
				reps = append(reps, n)
				queue = append(queue, n)
			}
		}
	}
	return reps
}

// wallpaperSpec is the static definition of a wallpaper group before closure.
type wallpaperSpec struct {
	iuc, orbifold, pg string
	lattice           LatticeType
	makeLattice       func() Lattice2D
	makeGens          func(l Lattice2D) []Isometry
}

// standard concrete lattices used for the 17 groups.
var (
	obliqueStd = ObliqueLattice(1, 1.35, Deg2Rad(72))
	rectStd    = RectangularLattice(1, 1.4)
	rhombicStd = RhombicLattice(1, 0.8)
	squareStd  = SquareLattice(1)
	hexStd     = HexagonalLattice(1)
)

var wallpaperSpecs = []wallpaperSpec{
	{"p1", "o", "C1", Oblique, func() Lattice2D { return obliqueStd }, func(l Lattice2D) []Isometry { return nil }},
	{"p2", "2222", "C2", Oblique, func() Lattice2D { return obliqueStd }, func(l Lattice2D) []Isometry { return []Isometry{linR2} }},
	{"pm", "**", "D1", Rectangular, func() Lattice2D { return rectStd }, func(l Lattice2D) []Isometry { return []Isometry{linMx} }},
	{"pg", "xx", "D1", Rectangular, func() Lattice2D { return rectStd }, func(l Lattice2D) []Isometry {
		return []Isometry{withTrans(linMy, l.V1.Scale(0.5))}
	}},
	{"cm", "*x", "D1", CenteredRectangular, func() Lattice2D { return rhombicStd }, func(l Lattice2D) []Isometry { return []Isometry{linMx} }},
	{"pmm", "*2222", "D2", Rectangular, func() Lattice2D { return rectStd }, func(l Lattice2D) []Isometry { return []Isometry{linMx, linMy} }},
	{"pmg", "22*", "D2", Rectangular, func() Lattice2D { return rectStd }, func(l Lattice2D) []Isometry {
		return []Isometry{linMx, withTrans(linMy, l.V1.Scale(0.5))}
	}},
	{"pgg", "22x", "D2", Rectangular, func() Lattice2D { return rectStd }, func(l Lattice2D) []Isometry {
		return []Isometry{withTrans(linMx, l.V2.Scale(0.5)), withTrans(linMy, l.V1.Scale(0.5))}
	}},
	{"cmm", "2*22", "D2", CenteredRectangular, func() Lattice2D { return rhombicStd }, func(l Lattice2D) []Isometry { return []Isometry{linMx, linMy} }},
	{"p4", "442", "C4", Square, func() Lattice2D { return squareStd }, func(l Lattice2D) []Isometry { return []Isometry{Rotation(math.Pi / 2)} }},
	{"p4m", "*442", "D4", Square, func() Lattice2D { return squareStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(math.Pi / 2), linMx}
	}},
	{"p4g", "4*2", "D4", Square, func() Lattice2D { return squareStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(math.Pi / 2), withTrans(linMx, l.V1.Add(l.V2).Scale(0.5))}
	}},
	{"p3", "333", "C3", Hexagonal, func() Lattice2D { return hexStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(2 * math.Pi / 3)}
	}},
	{"p3m1", "*333", "D3", Hexagonal, func() Lattice2D { return hexStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(2 * math.Pi / 3), linMy}
	}},
	{"p31m", "3*3", "D3", Hexagonal, func() Lattice2D { return hexStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(2 * math.Pi / 3), linMx}
	}},
	{"p6", "632", "C6", Hexagonal, func() Lattice2D { return hexStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(math.Pi / 3)}
	}},
	{"p6m", "*632", "D6", Hexagonal, func() Lattice2D { return hexStd }, func(l Lattice2D) []Isometry {
		return []Isometry{Rotation(math.Pi / 3), linMx}
	}},
}

// buildWallpaper realises a wallpaper group from its specification.
func buildWallpaper(s wallpaperSpec) WallpaperGroup {
	lat := s.makeLattice()
	gens := s.makeGens(lat)
	cosets := closeCosets(gens, lat)
	return WallpaperGroup{
		IUC:            s.iuc,
		Orbifold:       s.orbifold,
		Lattice:        s.lattice,
		PointGroupName: s.pg,
		lattice:        lat,
		generators:     gens,
		cosets:         cosets,
	}
}

// WallpaperGroups returns all 17 wallpaper groups in the conventional order
// (p1, p2, pm, pg, cm, pmm, pmg, pgg, cmm, p4, p4m, p4g, p3, p3m1, p31m, p6,
// p6m).
func WallpaperGroups() []WallpaperGroup {
	out := make([]WallpaperGroup, len(wallpaperSpecs))
	for i, s := range wallpaperSpecs {
		out[i] = buildWallpaper(s)
	}
	return out
}

// WallpaperGroupByIUC returns the wallpaper group with the given international
// symbol and reports whether it was found.
func WallpaperGroupByIUC(iuc string) (WallpaperGroup, bool) {
	for _, s := range wallpaperSpecs {
		if s.iuc == iuc {
			return buildWallpaper(s), true
		}
	}
	return WallpaperGroup{}, false
}

// WallpaperGroupByOrbifold returns the wallpaper group with the given orbifold
// symbol and reports whether it was found.
func WallpaperGroupByOrbifold(orb string) (WallpaperGroup, bool) {
	for _, s := range wallpaperSpecs {
		if s.orbifold == orb {
			return buildWallpaper(s), true
		}
	}
	return WallpaperGroup{}, false
}

// WallpaperIUCNames returns the 17 international symbols in conventional order.
func WallpaperIUCNames() []string {
	out := make([]string, len(wallpaperSpecs))
	for i, s := range wallpaperSpecs {
		out[i] = s.iuc
	}
	return out
}

// TranslationLattice returns the concrete translation lattice of the group.
func (g WallpaperGroup) TranslationLattice() Lattice2D { return g.lattice }

// Cosets returns the coset representatives of the group modulo its translation
// lattice. The number of representatives equals the order of the point group.
func (g WallpaperGroup) Cosets() []Isometry {
	out := make([]Isometry, len(g.cosets))
	copy(out, g.cosets)
	return out
}

// Generators returns the generating isometries used to build the group (not
// including the lattice translations).
func (g WallpaperGroup) Generators() []Isometry {
	out := make([]Isometry, len(g.generators))
	copy(out, g.generators)
	return out
}

// PointGroupOrder returns the order of the point group, equal to the number of
// coset representatives.
func (g WallpaperGroup) PointGroupOrder() int { return len(g.cosets) }

// MaxRotationOrder returns the highest order of rotation in the group.
func (g WallpaperGroup) MaxRotationOrder() int {
	max := 1
	for _, c := range g.cosets {
		if !c.IsDirect() {
			continue
		}
		a := c.RotationAngle()
		if approxEqualScalar(a, 0, 1e-9) {
			continue
		}
		k := int(math.Round(2 * math.Pi / math.Abs(a)))
		if k > max {
			max = k
		}
	}
	return max
}

// HasReflection reports whether the group contains a reflection.
func (g WallpaperGroup) HasReflection() bool {
	for _, c := range g.cosets {
		if c.Classify(1e-9).Kind == KindReflection {
			return true
		}
	}
	return false
}

// HasGlideReflection reports whether the group contains a glide reflection.
func (g WallpaperGroup) HasGlideReflection() bool {
	for _, c := range g.cosets {
		if c.Classify(1e-9).Kind == KindGlideReflection {
			return true
		}
	}
	return false
}

// GroupElements returns the isometries of the group whose translation parts lie
// within n lattice steps of the origin: every coset representative composed with
// each lattice translation i*V1 + j*V2 for i, j in [-n, n].
func (g WallpaperGroup) GroupElements(n int) []Isometry {
	if n < 0 {
		return nil
	}
	var out []Isometry
	for i := -n; i <= n; i++ {
		for j := -n; j <= n; j++ {
			t := TranslationVec(g.lattice.Point(i, j))
			for _, c := range g.cosets {
				out = append(out, t.Compose(c))
			}
		}
	}
	return out
}

// Orbit returns the images of the point p under GroupElements(n), deduplicated
// to within eps and sorted for determinism.
func (g WallpaperGroup) Orbit(p Point, n int, eps float64) []Point {
	var out []Point
	for _, e := range g.GroupElements(n) {
		q := e.Apply(p)
		dup := false
		for _, r := range out {
			if r.ApproxEqual(q, eps) {
				dup = true
				break
			}
		}
		if !dup {
			out = append(out, q)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if math.Abs(out[i].X-out[j].X) > eps {
			return out[i].X < out[j].X
		}
		return out[i].Y < out[j].Y
	})
	return out
}
