package groebner

import "sort"

// Buchberger computes a Gröbner basis of the ideal generated by gens with
// respect to the monomial order o, using Buchberger's algorithm with the
// coprime-leading-term criterion to discard trivial S-pairs. The returned basis
// is not necessarily reduced; use ReducedGroebnerBasis for the canonical form.
// Zero generators are ignored, and the empty generating set yields an empty
// basis.
func Buchberger(gens []Poly, o Order) []Poly {
	var g []Poly
	for _, p := range gens {
		if !p.IsZero() {
			g = append(g, p.Clone())
		}
	}
	if len(g) == 0 {
		return nil
	}
	n := g[0].nvars

	type pair struct{ i, j int }
	var pairs []pair
	for i := 0; i < len(g); i++ {
		for j := i + 1; j < len(g); j++ {
			pairs = append(pairs, pair{i, j})
		}
	}

	for len(pairs) > 0 {
		pr := pairs[0]
		pairs = pairs[1:]
		fi, fj := g[pr.i], g[pr.j]

		// Buchberger's first criterion: coprime leading monomials give an
		// S-polynomial that reduces to zero, so skip it.
		if fi.LeadingMonomial(o).Coprime(fj.LeadingMonomial(o)) {
			continue
		}

		s := SPolynomial(fi, fj, o)
		r := Remainder(s, g, o)
		if !r.IsZero() {
			r = r.Monic(o)
			g = append(g, r)
			k := len(g) - 1
			for t := 0; t < k; t++ {
				pairs = append(pairs, pair{t, k})
			}
		}
	}
	_ = n
	return g
}

// IsGroebnerBasis reports whether the set g is a Gröbner basis with respect to
// o, by verifying that every S-polynomial reduces to zero modulo g (Buchberger's
// criterion).
func IsGroebnerBasis(g []Poly, o Order) bool {
	for i := 0; i < len(g); i++ {
		for j := i + 1; j < len(g); j++ {
			if g[i].IsZero() || g[j].IsZero() {
				continue
			}
			s := SPolynomial(g[i], g[j], o)
			if !Remainder(s, g, o).IsZero() {
				return false
			}
		}
	}
	return true
}

// MinimalGroebnerBasis returns a minimal Gröbner basis obtained from g by making
// every element monic and discarding any element whose leading monomial is
// divisible by the leading monomial of another element.
func MinimalGroebnerBasis(g []Poly, o Order) []Poly {
	var monic []Poly
	for _, p := range g {
		if !p.IsZero() {
			monic = append(monic, p.Monic(o))
		}
	}
	keep := make([]bool, len(monic))
	for i := range monic {
		keep[i] = true
	}
	for i := range monic {
		if !keep[i] {
			continue
		}
		for j := range monic {
			if i == j || !keep[j] {
				continue
			}
			if monic[j].LeadingMonomial(o).Divides(monic[i].LeadingMonomial(o)) {
				keep[i] = false
				break
			}
		}
	}
	var out []Poly
	for i, p := range monic {
		if keep[i] {
			out = append(out, p)
		}
	}
	return out
}

// ReducedGroebnerBasis returns the unique reduced Gröbner basis of the ideal
// generated by gens with respect to o. Each element is monic and no monomial of
// any element is divisible by the leading monomial of any other. The basis is
// sorted in descending order of leading monomial, making it a canonical
// representative of the ideal.
func ReducedGroebnerBasis(gens []Poly, o Order) []Poly {
	g := MinimalGroebnerBasis(Buchberger(gens, o), o)
	// Inter-reduce: replace each element by its normal form modulo the others.
	changed := true
	for changed {
		changed = false
		for i := range g {
			rest := make([]Poly, 0, len(g)-1)
			for j := range g {
				if j != i {
					rest = append(rest, g[j])
				}
			}
			r := Remainder(g[i], rest, o)
			if !r.IsZero() {
				r = r.Monic(o)
			}
			if !r.Equal(g[i]) {
				g[i] = r
				changed = true
			}
		}
	}
	var out []Poly
	for _, p := range g {
		if !p.IsZero() {
			out = append(out, p)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		return o(out[i].LeadingMonomial(o), out[j].LeadingMonomial(o)) > 0
	})
	return out
}

// GroebnerBasis is a convenience wrapper that returns the reduced Gröbner basis
// of the given generators with respect to o.
func GroebnerBasis(gens []Poly, o Order) []Poly {
	return ReducedGroebnerBasis(gens, o)
}

// NormalForm returns the normal form (unique remainder) of f modulo the ideal
// with Gröbner basis g under the order o. Two polynomials are congruent modulo
// the ideal if and only if they have the same normal form.
func NormalForm(f Poly, g []Poly, o Order) Poly {
	return Remainder(f, g, o)
}

// InIdeal reports whether f belongs to the ideal generated by gens, by checking
// that its normal form modulo a Gröbner basis is zero.
func InIdeal(f Poly, gens []Poly, o Order) bool {
	g := ReducedGroebnerBasis(gens, o)
	return Remainder(f, g, o).IsZero()
}
