package groebner

// prependVars returns the polynomial re-embedded in a ring with k extra
// variables inserted before the existing ones (so old variable i becomes
// variable i+k). Used by the ideal-intersection construction.
func (p Poly) prependVars(k int) Poly {
	r := Poly{nvars: p.nvars + k}
	for _, t := range p.terms {
		m := make(Monomial, p.nvars+k)
		copy(m[k:], t.Mono)
		r.terms = append(r.terms, Term{Coeff: CloneRat(t.Coeff), Mono: m})
	}
	r.canonicalize()
	return r
}

// dropVarsFront returns the polynomial with the first k variables removed. It
// requires that those variables have exponent zero in every term.
func (p Poly) dropVarsFront(k int) Poly {
	r := Poly{nvars: p.nvars - k}
	for _, t := range p.terms {
		m := make(Monomial, p.nvars-k)
		copy(m, t.Mono[k:])
		r.terms = append(r.terms, Term{Coeff: CloneRat(t.Coeff), Mono: m})
	}
	r.canonicalize()
	return r
}

// Ideal represents a polynomial ideal by a list of generators in a fixed number
// of variables together with a default monomial order used by its methods.
type Ideal struct {
	nvars int
	order Order
	gens  []Poly
}

// NewIdeal builds the ideal generated by gens with the given default monomial
// order. The number of variables is taken from the first generator; if gens is
// empty the ideal is the zero ideal in zero variables (callers usually supply
// at least one generator).
func NewIdeal(o Order, gens ...Poly) Ideal {
	n := 0
	if len(gens) > 0 {
		n = gens[0].nvars
	}
	cp := make([]Poly, 0, len(gens))
	for _, g := range gens {
		cp = append(cp, g.Clone())
	}
	return Ideal{nvars: n, order: o, gens: cp}
}

// NewIdealN builds the ideal generated by gens in n variables with order o,
// allowing an explicit variable count (needed for the zero ideal).
func NewIdealN(n int, o Order, gens ...Poly) Ideal {
	cp := make([]Poly, 0, len(gens))
	for _, g := range gens {
		cp = append(cp, g.Clone())
	}
	return Ideal{nvars: n, order: o, gens: cp}
}

// Nvars returns the number of variables of the ambient ring.
func (id Ideal) Nvars() int { return id.nvars }

// Order returns the ideal's default monomial order.
func (id Ideal) Order() Order { return id.order }

// Generators returns a copy of the ideal's generating set.
func (id Ideal) Generators() []Poly {
	out := make([]Poly, len(id.gens))
	for i, g := range id.gens {
		out[i] = g.Clone()
	}
	return out
}

// WithOrder returns a copy of the ideal using a different default monomial
// order.
func (id Ideal) WithOrder(o Order) Ideal {
	return Ideal{nvars: id.nvars, order: o, gens: id.Generators()}
}

// GroebnerBasis returns a (reduced) Gröbner basis of the ideal with respect to
// its default order.
func (id Ideal) GroebnerBasis() []Poly {
	return ReducedGroebnerBasis(id.gens, id.order)
}

// ReducedGroebnerBasis returns the canonical reduced Gröbner basis of the ideal.
func (id Ideal) ReducedGroebnerBasis() []Poly {
	return ReducedGroebnerBasis(id.gens, id.order)
}

// Contains reports whether the polynomial f is a member of the ideal.
func (id Ideal) Contains(f Poly) bool {
	return Remainder(f, id.GroebnerBasis(), id.order).IsZero()
}

// IsUnit reports whether the ideal is the whole ring, i.e. it contains the
// constant 1 (equivalently its reduced Gröbner basis is {1}).
func (id Ideal) IsUnit() bool {
	g := id.GroebnerBasis()
	return len(g) == 1 && g[0].IsConstant() && !g[0].IsZero()
}

// IsZero reports whether the ideal is the zero ideal.
func (id Ideal) IsZero() bool {
	return len(id.GroebnerBasis()) == 0
}

// Equal reports whether two ideals are equal, by comparing their reduced
// Gröbner bases under a common order (the receiver's order).
func (id Ideal) Equal(other Ideal) bool {
	a := id.GroebnerBasis()
	b := ReducedGroebnerBasis(other.gens, id.order)
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !a[i].Equal(b[i]) {
			return false
		}
	}
	return true
}

// Sum returns the ideal sum I + J, generated by the union of the two generating
// sets. It uses the receiver's order.
func (id Ideal) Sum(other Ideal) Ideal {
	gens := append(id.Generators(), other.Generators()...)
	return Ideal{nvars: id.nvars, order: id.order, gens: gens}
}

// Product returns the ideal product I*J, generated by all pairwise products of
// generators. It uses the receiver's order.
func (id Ideal) Product(other Ideal) Ideal {
	var gens []Poly
	for _, a := range id.gens {
		for _, b := range other.gens {
			gens = append(gens, a.Mul(b))
		}
	}
	return Ideal{nvars: id.nvars, order: id.order, gens: gens}
}

// Intersect returns the ideal intersection I ∩ J. It uses the standard
// elimination construction: in a ring with one extra variable t it forms the
// ideal generated by t*f_i and (1-t)*g_j and eliminates t.
func (id Ideal) Intersect(other Ideal) Ideal {
	n := id.nvars
	var gens []Poly
	t := Var(n+1, 0) // the fresh variable
	oneMinusT := One(n + 1).Sub(t)
	for _, f := range id.gens {
		gens = append(gens, f.prependVars(1).Mul(t))
	}
	for _, g := range other.gens {
		gens = append(gens, g.prependVars(1).Mul(oneMinusT))
	}
	gb := ReducedGroebnerBasis(gens, EliminationOrder(1))
	var result []Poly
	for _, p := range gb {
		if !p.DependsOn(0) {
			result = append(result, p.dropVarsFront(1))
		}
	}
	return Ideal{nvars: n, order: id.order, gens: result}
}

// Quotient returns the ideal quotient (colon ideal) I : J = { f : f*J ⊆ I }.
// It is computed as the intersection over the generators g of J of the single
// quotients I : (g).
func (id Ideal) Quotient(other Ideal) Ideal {
	result := id.QuotientElem(other.gens[0])
	for _, g := range other.gens[1:] {
		result = result.Intersect(id.QuotientElem(g))
	}
	return result
}

// QuotientElem returns the ideal quotient I : (h) for a single polynomial h,
// using the identity h*(I:h) = I ∩ (h): it intersects I with the principal
// ideal (h) and divides each resulting generator by h.
func (id Ideal) QuotientElem(h Poly) Ideal {
	principal := Ideal{nvars: id.nvars, order: id.order, gens: []Poly{h.Clone()}}
	inter := id.Intersect(principal)
	var gens []Poly
	for _, p := range inter.gens {
		if q, ok := ExactQuotient(p, h, id.order); ok {
			gens = append(gens, q)
		}
	}
	if len(gens) == 0 {
		gens = []Poly{Zero(id.nvars)}
	}
	return Ideal{nvars: id.nvars, order: id.order, gens: gens}
}

// Eliminate returns the elimination ideal obtained by eliminating the first k
// variables, i.e. I ∩ Q[x_{k+1}, ..., x_n], still embedded in the original ring
// (the eliminated variables simply do not occur). It uses an elimination order.
func (id Ideal) Eliminate(k int) Ideal {
	gb := ReducedGroebnerBasis(id.gens, EliminationOrder(k))
	var result []Poly
	for _, p := range gb {
		eliminated := false
		for i := 0; i < k; i++ {
			if p.DependsOn(i) {
				eliminated = true
				break
			}
		}
		if !eliminated {
			result = append(result, p)
		}
	}
	return Ideal{nvars: id.nvars, order: id.order, gens: result}
}

// EliminationIdeal is the free-function form of Eliminate: it returns
// generators of the k-th elimination ideal of the given generators.
func EliminationIdeal(gens []Poly, k int, o Order) []Poly {
	gb := ReducedGroebnerBasis(gens, EliminationOrder(k))
	var result []Poly
	for _, p := range gb {
		keep := true
		for i := 0; i < k; i++ {
			if p.DependsOn(i) {
				keep = false
				break
			}
		}
		if keep {
			result = append(result, p)
		}
	}
	return result
}

// IsZeroDimensional reports whether the ideal is zero-dimensional, i.e. the
// quotient ring is a finite-dimensional vector space over Q, equivalently the
// variety over the algebraic closure is finite. It checks that for every
// variable some leading monomial of the reduced Gröbner basis is a pure power
// of that variable. The unit ideal (empty variety) is considered
// zero-dimensional.
func (id Ideal) IsZeroDimensional() bool {
	gb := ReducedGroebnerBasis(id.gens, GrevlexOrder())
	if len(gb) == 0 {
		return false // zero ideal: whole affine space, positive-dimensional (n>0)
	}
	if len(gb) == 1 && gb[0].IsConstant() {
		return true // unit ideal
	}
	o := GrevlexOrder()
	for v := 0; v < id.nvars; v++ {
		found := false
		for _, p := range gb {
			lm := p.LeadingMonomial(o)
			pure := lm[v] > 0
			if pure {
				for w := 0; w < id.nvars; w++ {
					if w != v && lm[w] != 0 {
						pure = false
						break
					}
				}
			}
			if pure {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}

// QuotientBasis returns a monomial basis of the quotient ring Q[x]/I as a
// Q-vector space, valid when the ideal is zero-dimensional. These are exactly
// the standard monomials: the monomials not divisible by any leading monomial
// of the Gröbner basis. The boolean result is false when the ideal is not
// zero-dimensional.
func (id Ideal) QuotientBasis() ([]Monomial, bool) {
	if !id.IsZeroDimensional() {
		return nil, false
	}
	o := GrevlexOrder()
	gb := ReducedGroebnerBasis(id.gens, o)
	if len(gb) == 1 && gb[0].IsConstant() {
		return nil, true // unit ideal: quotient is zero
	}
	// Per-variable degree bounds from the pure-power leading monomials.
	bound := make([]int, id.nvars)
	for v := 0; v < id.nvars; v++ {
		for _, p := range gb {
			lm := p.LeadingMonomial(o)
			pure := lm[v] > 0
			for w := 0; w < id.nvars; w++ {
				if w != v && lm[w] != 0 {
					pure = false
				}
			}
			if pure {
				if bound[v] == 0 || lm[v] < bound[v] {
					bound[v] = lm[v]
				}
			}
		}
	}
	var lms []Monomial
	for _, p := range gb {
		lms = append(lms, p.LeadingMonomial(o))
	}
	var basis []Monomial
	cur := make(Monomial, id.nvars)
	var rec func(i int)
	rec = func(i int) {
		if i == id.nvars {
			for _, lm := range lms {
				if lm.Divides(cur) {
					return
				}
			}
			basis = append(basis, cur.Clone())
			return
		}
		for e := 0; e < bound[i]; e++ {
			cur[i] = e
			rec(i + 1)
		}
		cur[i] = 0
	}
	rec(0)
	return basis, true
}

// VectorSpaceDimension returns the dimension of Q[x]/I as a Q-vector space for a
// zero-dimensional ideal, equal to the number of solutions counted with
// multiplicity over the algebraic closure. The boolean result is false when the
// ideal is not zero-dimensional.
func (id Ideal) VectorSpaceDimension() (int, bool) {
	b, ok := id.QuotientBasis()
	if !ok {
		return 0, false
	}
	return len(b), true
}
