package groebner

import "math/big"

// Ring bundles the number of variables, their display names, and a default
// monomial order. It offers convenient constructors and operations so that
// callers do not have to repeat the variable count and order everywhere.
type Ring struct {
	nvars int
	names []string
	order Order
}

// NewRing returns a ring in n variables with the given monomial order and the
// default variable names x1, ..., xn.
func NewRing(n int, o Order) Ring {
	return Ring{nvars: n, names: defaultVarNames(n), order: o}
}

// NewNamedRing returns a ring whose variables carry the supplied names, in the
// given monomial order.
func NewNamedRing(names []string, o Order) Ring {
	cp := append([]string(nil), names...)
	return Ring{nvars: len(cp), names: cp, order: o}
}

// Nvars returns the number of variables of the ring.
func (r Ring) Nvars() int { return r.nvars }

// Order returns the ring's default monomial order.
func (r Ring) Order() Order { return r.order }

// Names returns a copy of the variable display names.
func (r Ring) Names() []string { return append([]string(nil), r.names...) }

// WithOrder returns a copy of the ring using a different default order.
func (r Ring) WithOrder(o Order) Ring {
	return Ring{nvars: r.nvars, names: r.Names(), order: o}
}

// Zero returns the zero polynomial of the ring.
func (r Ring) Zero() Poly { return Zero(r.nvars) }

// One returns the constant polynomial 1 of the ring.
func (r Ring) One() Poly { return One(r.nvars) }

// Constant returns the constant polynomial c of the ring.
func (r Ring) Constant(c *big.Rat) Poly { return Constant(r.nvars, c) }

// ConstantInt returns the constant polynomial equal to the integer c.
func (r Ring) ConstantInt(c int64) Poly { return ConstantInt(r.nvars, c) }

// Var returns the i-th variable of the ring as a polynomial.
func (r Ring) Var(i int) Poly { return Var(r.nvars, i) }

// Vars returns all variables of the ring as polynomials.
func (r Ring) Vars() []Poly { return Vars(r.nvars) }

// Format renders a polynomial using the ring's variable names.
func (r Ring) Format(p Poly) string { return p.Format(r.names) }

// SPolynomial returns the S-polynomial of f and g under the ring's order.
func (r Ring) SPolynomial(f, g Poly) Poly { return SPolynomial(f, g, r.order) }

// Divide performs multivariate division under the ring's order.
func (r Ring) Divide(f Poly, divisors []Poly) DivisionResult {
	return MultivariateDivide(f, divisors, r.order)
}

// Remainder returns the remainder of dividing f by the divisors under the
// ring's order.
func (r Ring) Remainder(f Poly, divisors []Poly) Poly {
	return Remainder(f, divisors, r.order)
}

// GroebnerBasis returns the reduced Gröbner basis of the given generators under
// the ring's order.
func (r Ring) GroebnerBasis(gens []Poly) []Poly {
	return ReducedGroebnerBasis(gens, r.order)
}

// Ideal returns the ideal generated by gens with the ring's order.
func (r Ring) Ideal(gens ...Poly) Ideal {
	return NewIdealN(r.nvars, r.order, gens...)
}

// LeadingTerm returns the leading term of p under the ring's order.
func (r Ring) LeadingTerm(p Poly) Term { return p.LeadingTerm(r.order) }
