package crypto

import (
	"math/big"
	"math/rand"
	"testing"
)

func TestBabyStepGiantStep(t *testing.T) {
	// g=2 is a primitive root mod 29 (order 28).
	p := bi(29)
	order := bi(28)
	for x := int64(0); x < 28; x++ {
		h := ModExp(bi(2), bi(x), p)
		got, err := BabyStepGiantStep(bi(2), h, p, order)
		if err != nil {
			t.Fatalf("BSGS x=%d err %v", x, err)
		}
		// Verify g^got == h (got may equal x within the order).
		if ModExp(bi(2), got, p).Cmp(h) != 0 {
			t.Errorf("BSGS: 2^%d != %d mod 29", got.Int64(), h.Int64())
		}
	}
	// Known: 2^26 ≡ 22 (mod 29), so the discrete log of 22 base 2 is 26.
	got, err := DiscreteLog(bi(2), bi(22), bi(29))
	if err != nil || got.Int64() != 26 {
		t.Errorf("DiscreteLog(2,22,29)=%v err=%v want 26", got, err)
	}
	// No solution case: element outside subgroup generated by a non-generator.
	if _, err := BabyStepGiantStep(bi(4), bi(2), bi(29), bi(14)); err == nil {
		t.Log("note: 4 generates subgroup; 2 not necessarily in it")
	}
}

func TestRSARoundTrip(t *testing.T) {
	rng := rand.New(rand.NewSource(2024))
	key, err := GenerateRSAKey(128, nil, rng)
	if err != nil {
		t.Fatal(err)
	}
	msg := bi(42)
	ct, err := RSAEncrypt(key.Public, msg)
	if err != nil {
		t.Fatal(err)
	}
	pt, err := RSADecrypt(key, ct)
	if err != nil {
		t.Fatal(err)
	}
	if pt.Cmp(msg) != 0 {
		t.Errorf("RSA round trip: got %v want %v", pt, msg)
	}
	// CRT decryption must match.
	ptCRT, err := RSADecryptCRT(key, ct)
	if err != nil {
		t.Fatal(err)
	}
	if ptCRT.Cmp(msg) != 0 {
		t.Errorf("RSADecryptCRT: got %v want %v", ptCRT, msg)
	}
	// Signature round trip.
	sig, err := RSASign(key, msg)
	if err != nil {
		t.Fatal(err)
	}
	if !RSAVerify(key.Public, msg, sig) {
		t.Error("RSAVerify rejected a valid signature")
	}
	if RSAVerify(key.Public, bi(43), sig) {
		t.Error("RSAVerify accepted a forged message")
	}
}

func TestRSADeterministic(t *testing.T) {
	k1, _ := GenerateRSAKey(96, nil, rand.New(rand.NewSource(9)))
	k2, _ := GenerateRSAKey(96, nil, rand.New(rand.NewSource(9)))
	if k1.Public.N.Cmp(k2.Public.N) != 0 || k1.D.Cmp(k2.D) != 0 {
		t.Error("RSA key generation is not deterministic under identical seeds")
	}
}

func TestDiffieHellman(t *testing.T) {
	rng := rand.New(rand.NewSource(77))
	params := GenerateDHParams(64, rng)
	a := params.DHGeneratePrivate(rng)
	b := params.DHGeneratePrivate(rng)
	A := params.DHPublicKey(a)
	B := params.DHPublicKey(b)
	sa, err := params.DHSharedSecret(a, B)
	if err != nil {
		t.Fatal(err)
	}
	sb, err := params.DHSharedSecret(b, A)
	if err != nil {
		t.Fatal(err)
	}
	if sa.Cmp(sb) != 0 {
		t.Errorf("DH shared secrets differ: %v vs %v", sa, sb)
	}
}

func TestElGamal(t *testing.T) {
	rng := rand.New(rand.NewSource(55))
	key := GenerateElGamalKey(64, rng)
	msg := bi(12345)
	c1, c2, err := ElGamalEncrypt(key.Public, msg, rng)
	if err != nil {
		t.Fatal(err)
	}
	dec, err := ElGamalDecrypt(key, c1, c2)
	if err != nil {
		t.Fatal(err)
	}
	if dec.Cmp(msg) != 0 {
		t.Errorf("ElGamal round trip: got %v want %v", dec, msg)
	}
}

func TestShamir(t *testing.T) {
	rng := rand.New(rand.NewSource(1))
	prime := bi(2087) // a prime field
	secret := bi(1234)
	shares, err := SplitSecret(secret, 3, 5, prime, rng)
	if err != nil {
		t.Fatal(err)
	}
	// Any 3 of the 5 shares reconstruct the secret.
	subsets := [][]int{{0, 1, 2}, {1, 3, 4}, {0, 2, 4}, {2, 3, 4}}
	for _, idx := range subsets {
		sub := []Share{shares[idx[0]], shares[idx[1]], shares[idx[2]]}
		got, err := CombineShares(sub, prime)
		if err != nil {
			t.Fatal(err)
		}
		if got.Cmp(secret) != 0 {
			t.Errorf("Shamir combine %v = %v want %v", idx, got, secret)
		}
	}
	// Using all shares also works.
	all, err := CombineShares(shares, prime)
	if err != nil || all.Cmp(secret) != 0 {
		t.Errorf("Shamir combine all = %v err %v", all, err)
	}
	// Two shares (below threshold) generally yield the wrong secret.
	two, _ := CombineShares([]Share{shares[0], shares[1]}, prime)
	if two.Cmp(secret) == 0 {
		t.Log("note: 2 shares happened to reconstruct (coincidence)")
	}
}

func TestEvaluatePolynomial(t *testing.T) {
	// p(x) = 3 + 2x + x^2 ; p(4)=3+8+16=27 mod 100.
	coeffs := []*big.Int{bi(3), bi(2), bi(1)}
	if got := EvaluatePolynomial(coeffs, bi(4), bi(100)); got.Int64() != 27 {
		t.Errorf("EvaluatePolynomial=%d want 27", got.Int64())
	}
}

func BenchmarkGenerateRSAKey(b *testing.B) {
	for i := 0; i < b.N; i++ {
		rng := rand.New(rand.NewSource(int64(i)))
		if _, err := GenerateRSAKey(256, nil, rng); err != nil {
			b.Fatal(err)
		}
	}
}
