package stats

import (
	"math"
	"math/rand"
)

// ContinuousSampler is implemented by continuous distributions that can draw a
// single random variate. The caller supplies the *math/rand.Rand source, so the
// stream is fully deterministic for a given seed: build it with
// rand.New(rand.NewSource(seed)) for reproducible sampling.
type ContinuousSampler interface {
	// Sample returns one variate drawn from the distribution using r.
	Sample(r *rand.Rand) float64
}

// DiscreteSampler is implemented by discrete distributions that can draw a
// single integer variate. As with ContinuousSampler the caller owns the
// *math/rand.Rand source, keeping the sequence reproducible for a fixed seed.
type DiscreteSampler interface {
	// SampleInt returns one integer variate drawn from the distribution using r.
	SampleInt(r *rand.Rand) int
}

// statsPolarNormal returns one standard-normal variate using the Marsaglia
// polar method. It draws pairs (u, v) uniformly from the unit square, rejects
// those outside the open unit disc, and applies the polar transform. Only one
// of the two normals the method produces is returned; the path allocates
// nothing and terminates with probability 1.
func statsPolarNormal(r *rand.Rand) float64 {
	for {
		u := 2*r.Float64() - 1
		v := 2*r.Float64() - 1
		s := u*u + v*v
		if s > 0 && s < 1 {
			return u * math.Sqrt(-2*math.Log(s)/s)
		}
	}
}

// statsSampleGamma draws one variate from a Gamma(shape, scale) distribution
// using the Marsaglia–Tsang squeeze. For shape >= 1 it uses the rejection
// scheme with the cheap squeeze u < 1 - 0.0331·x⁴ before the expensive
// logarithmic test. For shape < 1 it boosts a Gamma(shape+1) variate by
// U^(1/shape). It is the workhorse behind the gamma, beta, chi-squared, F and
// Student's t samplers, and allocates nothing.
func statsSampleGamma(r *rand.Rand, shape, scale float64) float64 {
	if shape < 1 {
		u := r.Float64()
		return statsSampleGamma(r, shape+1, scale) * math.Pow(u, 1/shape)
	}
	d := shape - 1.0/3.0
	c := 1.0 / math.Sqrt(9*d)
	for {
		var x, v float64
		for {
			x = statsPolarNormal(r)
			v = 1 + c*x
			if v > 0 {
				break
			}
		}
		v = v * v * v
		u := r.Float64()
		if u < 1-0.0331*x*x*x*x {
			return d * v * scale
		}
		if math.Log(u) < 0.5*x*x+d*(1-v+math.Log(v)) {
			return d * v * scale
		}
	}
}

// Sample draws a single variate from the uniform distribution on [A, B) using a
// single call to r.Float64: A + (B-A)·U.
func (u Uniform) Sample(r *rand.Rand) float64 {
	return u.A + (u.B-u.A)*r.Float64()
}

// Sample draws a single variate from the exponential distribution using r via
// inverse-CDF sampling, reusing the distribution's Quantile method.
func (e Exponential) Sample(r *rand.Rand) float64 {
	return e.Quantile(r.Float64())
}

// Sample draws a single variate from the Weibull distribution using r via
// inverse-CDF sampling, reusing the distribution's Quantile method.
func (w Weibull) Sample(r *rand.Rand) float64 {
	return w.Quantile(r.Float64())
}

// Sample draws a single variate from the log-normal distribution using r via
// inverse-CDF sampling, reusing the distribution's Quantile method.
func (l LogNormal) Sample(r *rand.Rand) float64 {
	return l.Quantile(r.Float64())
}

// Sample draws a single variate from the normal distribution using r. It scales
// and shifts a standard-normal variate generated by the Marsaglia polar method:
// Mu + Sigma·Z.
func (n Normal) Sample(r *rand.Rand) float64 {
	return n.Mu + n.Sigma*statsPolarNormal(r)
}

// Sample draws a single variate from the gamma distribution using r via the
// Marsaglia–Tsang squeeze.
func (g Gamma) Sample(r *rand.Rand) float64 {
	return statsSampleGamma(r, g.Shape, g.Scale)
}

// Sample draws a single variate from the chi-squared distribution using r, as a
// Gamma(K/2, 2) variate.
func (c ChiSquared) Sample(r *rand.Rand) float64 {
	return Gamma{Shape: c.K / 2, Scale: 2}.Sample(r)
}

// Sample draws a single variate from the beta distribution using r, as
// G1/(G1+G2) where G1 ~ Gamma(Alpha, 1) and G2 ~ Gamma(Beta, 1) are independent.
func (b Beta) Sample(r *rand.Rand) float64 {
	g1 := statsSampleGamma(r, b.Alpha, 1)
	g2 := statsSampleGamma(r, b.Beta, 1)
	return g1 / (g1 + g2)
}

// Sample draws a single variate from Student's t distribution using r, as
// Z / sqrt(V/Nu) where Z is standard normal and V ~ ChiSquared(Nu) is
// independent.
func (t StudentT) Sample(r *rand.Rand) float64 {
	z := statsPolarNormal(r)
	v := ChiSquared{K: t.Nu}.Sample(r)
	return z / math.Sqrt(v/t.Nu)
}

// Sample draws a single variate from the F distribution using r, as the ratio
// (X1/D1)/(X2/D2) of two independent chi-squared variates scaled by their
// degrees of freedom.
func (f FDist) Sample(r *rand.Rand) float64 {
	x1 := ChiSquared{K: f.D1}.Sample(r)
	x2 := ChiSquared{K: f.D2}.Sample(r)
	return (x1 / f.D1) / (x2 / f.D2)
}

// statsPoissonKnuth draws one Poisson(lambda) variate by the Knuth product
// method, multiplying uniforms until the running product drops below e^-lambda.
// It is used for small lambda, where the expected number of iterations is
// lambda + 1.
func statsPoissonKnuth(r *rand.Rand, lambda float64) int {
	limit := math.Exp(-lambda)
	prod := 1.0
	k := 0
	for {
		prod *= r.Float64()
		if prod <= limit {
			return k
		}
		k++
	}
}

// statsPoissonPTRS draws one Poisson(lambda) variate by Hörmann's transformed
// rejection with squeeze (PTRS). It runs in constant expected time independent
// of lambda and is used for lambda >= 30.
func statsPoissonPTRS(r *rand.Rand, lambda float64) int {
	b := 0.931 + 2.53*math.Sqrt(lambda)
	a := -0.059 + 0.02483*b
	invAlpha := 1.1239 + 1.1328/(b-3.4)
	vr := 0.9277 - 3.6224/(b-2)
	for {
		u := r.Float64() - 0.5
		v := r.Float64()
		us := 0.5 - math.Abs(u)
		k := int(math.Floor((2*a/us+b)*u + lambda + 0.43))
		if us >= 0.07 && v <= vr {
			return k
		}
		if k < 0 || (us < 0.013 && v > us) {
			continue
		}
		if math.Log(v)+math.Log(invAlpha)-math.Log(a/(us*us)+b) <=
			-lambda+float64(k)*math.Log(lambda)-gammaLn(float64(k)+1) {
			return k
		}
	}
}

// SampleInt draws a single count from the Poisson distribution using r. It uses
// Knuth's product method for Lambda < 30 and the constant-time PTRS
// transformed-rejection method for larger Lambda.
func (p Poisson) SampleInt(r *rand.Rand) int {
	if p.Lambda <= 0 {
		return 0
	}
	if p.Lambda < 30 {
		return statsPoissonKnuth(r, p.Lambda)
	}
	return statsPoissonPTRS(r, p.Lambda)
}

// statsBinomialInversion draws one Binomial(n, p) count by inversion (the BINV
// algorithm), walking the CDF from k=0 with a single uniform. It is efficient
// only while the mean n·p is small, so callers gate it on that condition.
func statsBinomialInversion(r *rand.Rand, n int, p float64) int {
	q := 1 - p
	s := p / q
	a := float64(n+1) * s
	term := math.Pow(q, float64(n))
	u := r.Float64()
	k := 0
	for u > term {
		u -= term
		k++
		if k > n {
			return n
		}
		term *= a/float64(k) - s
	}
	return k
}

// statsBinomialTrials draws one Binomial(n, p) count by summing n independent
// Bernoulli(p) trials. It is used for large n·p, where inversion would need too
// many CDF steps.
func statsBinomialTrials(r *rand.Rand, n int, p float64) int {
	k := 0
	for i := 0; i < n; i++ {
		if r.Float64() < p {
			k++
		}
	}
	return k
}

// SampleInt draws a single count of successes from the binomial distribution
// using r. It samples the smaller tail by reflecting when P > 0.5, then uses
// CDF inversion while the mean N·P is small (< 30) and a per-trial Bernoulli
// sum otherwise.
func (b Binomial) SampleInt(r *rand.Rand) int {
	if b.N <= 0 {
		return 0
	}
	p := b.P
	if p <= 0 {
		return 0
	}
	if p >= 1 {
		return b.N
	}
	flip := false
	if p > 0.5 {
		p = 1 - p
		flip = true
	}
	var k int
	if float64(b.N)*p < 30 {
		k = statsBinomialInversion(r, b.N, p)
	} else {
		k = statsBinomialTrials(r, b.N, p)
	}
	if flip {
		k = b.N - k
	}
	return k
}

// SampleInt draws a single variate from the geometric distribution using r via
// inverse-transform sampling, floor(ln(1-U)/ln(1-P)).
func (g Geometric) SampleInt(r *rand.Rand) int {
	u := r.Float64()
	return int(math.Floor(math.Log(1-u) / math.Log(1-g.P)))
}

// SampleInt draws a single count of failures from the negative binomial
// distribution using r via the Poisson–gamma mixture: a Gamma(R, (1-P)/P) rate
// is drawn first and then used as the mean of a Poisson variate.
func (nb NegativeBinomial) SampleInt(r *rand.Rand) int {
	lambda := statsSampleGamma(r, nb.R, (1-nb.P)/nb.P)
	return Poisson{Lambda: lambda}.SampleInt(r)
}

// SampleInt draws a single count of successes from the hypergeometric
// distribution using r by simulating an urn drawn without replacement: Draws
// items are removed from a population of N containing K successes, each removal
// succeeding in proportion to the successes remaining.
func (h Hypergeometric) SampleInt(r *rand.Rand) int {
	good := h.K
	remaining := h.N
	k := 0
	for i := 0; i < h.Draws; i++ {
		if r.Float64()*float64(remaining) < float64(good) {
			k++
			good--
		}
		remaining--
	}
	return k
}

// SampleN draws n independent variates from d using r and returns them in a new
// slice. It is a convenience for building Monte-Carlo inputs and test data.
func SampleN(d ContinuousSampler, n int, r *rand.Rand) []float64 {
	out := make([]float64, n)
	for i := range out {
		out[i] = d.Sample(r)
	}
	return out
}

// SampleIntN draws n independent integer variates from d using r and returns
// them in a new slice.
func SampleIntN(d DiscreteSampler, n int, r *rand.Rand) []int {
	out := make([]int, n)
	for i := range out {
		out[i] = d.SampleInt(r)
	}
	return out
}

// Shuffle permutes xs in place using r with the Fisher–Yates algorithm, giving
// each of the len(xs)! orderings equal probability.
func Shuffle(xs []float64, r *rand.Rand) {
	for i := len(xs) - 1; i > 0; i-- {
		j := r.Intn(i + 1)
		xs[i], xs[j] = xs[j], xs[i]
	}
}

// Resample returns a bootstrap sample of xs: a new slice of the same length
// whose elements are drawn from xs uniformly with replacement using r. It
// returns an empty (non-nil) slice when xs is empty.
func Resample(xs []float64, r *rand.Rand) []float64 {
	n := len(xs)
	out := make([]float64, n)
	for i := range out {
		out[i] = xs[r.Intn(n)]
	}
	return out
}
