package ecc

import "math/big"

// NamedCurve bundles a curve over GF(p) with the standard domain parameters used
// by cryptographic protocols: a fixed base point G that generates a subgroup of
// prime order N, and the cofactor H = #E / N.
type NamedCurve struct {
	// Curve is the underlying short Weierstrass curve over GF(p).
	Curve *CurveFp
	// G is the standard base point (generator) of the prime-order subgroup.
	G PointFp
	// N is the prime order of the subgroup generated by G.
	N *big.Int
	// H is the cofactor, the index of the subgroup <G> in the full group.
	H *big.Int
}

// eccHex parses a hexadecimal string into a big.Int, panicking on malformed
// input. It is used only for the compiled-in domain parameters below.
func eccHex(s string) *big.Int {
	n, ok := new(big.Int).SetString(s, 16)
	if !ok {
		panic("ecc: invalid hexadecimal constant " + s)
	}
	return n
}

// Secp256k1 returns the standard SEC 2 curve secp256k1, y^2 = x^3 + 7 over a
// 256-bit prime field, together with its generator, subgroup order and cofactor
// 1. This is the curve used by, among others, Bitcoin.
func Secp256k1() NamedCurve {
	p := eccHex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F")
	c, err := NewCurveFp(big.NewInt(0), big.NewInt(7), p)
	if err != nil {
		panic("ecc: secp256k1 parameters are invalid: " + err.Error())
	}
	gx := eccHex("79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798")
	gy := eccHex("483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8")
	return NamedCurve{
		Curve: c,
		G:     PointFp{X: gx, Y: gy},
		N:     eccHex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"),
		H:     big.NewInt(1),
	}
}

// P256 returns the NIST P-256 curve (also called secp256r1 or prime256v1),
// y^2 = x^3 - 3*x + B over a 256-bit prime field, together with its generator,
// subgroup order and cofactor 1.
func P256() NamedCurve {
	p := eccHex("FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF")
	b := eccHex("5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B")
	c, err := NewCurveFp(big.NewInt(-3), b, p)
	if err != nil {
		panic("ecc: P-256 parameters are invalid: " + err.Error())
	}
	gx := eccHex("6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296")
	gy := eccHex("4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5")
	return NamedCurve{
		Curve: c,
		G:     PointFp{X: gx, Y: gy},
		N:     eccHex("FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"),
		H:     big.NewInt(1),
	}
}
